Add update version action to po smart contract
hyperledger/grid pull request #1005
Opened 2021-10-28 21:28 UTC by shannynalayna

This adds an implementation to the po smart contract for the "update version" action.

2021-11-03 20:09 UTC, leebradley requested changes

2021-11-03 20:09 UTC, leebradley commented on contracts/purchase_order/src/handler.rs
> +    if desired_workflow_state.has_constraint(&WorkflowConstraint::Complete.to_string()) {
I'm thinking most of this validation would be useful regardless of whether the version is complete.

2021-11-03 20:22 UTC, shannynalayna commented on contracts/purchase_order/src/handler.rs
> +    if desired_workflow_state.has_constraint(&WorkflowConstraint::Complete.to_string()) {
I'm gonna put up a PR to add validation for all of the PO payloads before they're handed off into the individual funcs and then will rebase this one :) without this check probably

2021-11-03 21:53 UTC, shannynalayna commented on contracts/purchase_order/src/state.rs
> +        }
Thanks for this!

2021-11-05 14:56 UTC, shannynalayna commented
This will need to be rebased on #1015

2021-11-05 19:16 UTC, leebradley approved these changes

2021-11-05 19:38 UTC, leebradley submitted a review, later dismissed

2021-11-05 20:28 UTC, dnewh submitted a review, later dismissed

2021-11-08 16:22 UTC, leebradley approved these changes

2021-11-10 18:24 UTC, agunde406 approved these changes

2021-11-10 21:23 UTC, merged