Add PO list/show CLI functionality
hyperledger/grid pull request #1008
Opened 2021-11-01 15:23 UTC by dnewh

This PR updates the Grid CLI to include functionality to list and show a Grid Purchase Order. This includes changes to the Purchase Order client to update the structs and functions to align with the RFC and current discussions. It also includes updates to the version and revision list/show commands to use the new display utility functions/patterns introduced here.

2021-11-04 13:55 UTC, leebradley requested changes

2021-11-04 13:55 UTC, leebradley commented on cli/man/grid-po-show.1.md
>  Revision 4:
Should this be updated to add `Created At` and `Submitter` (same with output below)?

2021-11-04 15:19 UTC, shannynalayna commented on sdk/src/client/purchase_order/reqwest.rs
> +pub struct PurchaseOrderDto {
Is this struct being used in the purchase_order/mod file? If so, this should probably be pub(crate) or something to that affect as we don't want these internal structs publicly available

2021-11-04 15:44 UTC, dnewh commented on sdk/src/client/purchase_order/reqwest.rs
> +pub struct PurchaseOrderDto {
this was a mistake. Should not have been changed.

2021-11-04 16:24 UTC, dnewh commented on cli/man/grid-po-show.1.md
>  Revision 4:
Version does not have these fields. Added the revision fields here

2021-11-04 16:27 UTC, dnewh commented on cli/src/main.rs
> +                ("list", Some(_)) => {
yes

2021-11-04 17:30 UTC, dnewh commented on cli/src/actions/purchase_orders.rs
> +    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
added

2021-11-04 17:30 UTC, dnewh commented on cli/src/actions/purchase_orders.rs
> +                .map_err(|_| CliError::ActionError("Cannot format as JSON".to_string()))?;
updated

2021-11-04 18:08 UTC, dnewh commented on sdk/src/client/reqwest.rs
> +    let mut query_params = vec![];
updated

2021-11-04 18:08 UTC, dnewh commented on sdk/src/client/reqwest.rs
> +    let mut query_params = vec![];
updated

2021-11-04 18:32 UTC, leebradley requested changes

2021-11-04 18:32 UTC, leebradley commented on cli/src/actions/purchase_orders.rs
> +        let display = "Revision 1:\n\tCreated At        1970-05-23T21:21:18+00:00\n\tSubmitter         0200ef9ab9243baee54f61a64d66aeb1d33bb063f16dfaa72e61886b9870c2b7ee\n\n<tag></tag>";
Just for ease of reading and so it doesn't exceed the maximum line width:
```rust
        let display = "\
Revision 1:
	Created At        1970-05-23T21:21:18+00:00
	Submitter         0200ef9ab9243baee54f61a64d66aeb1d33bb063f16dfaa72e61886b9870c2b7ee

<tag></tag>";
```

2021-11-04 18:32 UTC, leebradley commented on cli/src/actions/purchase_orders.rs
> +        let display = "Version 1:\n\tWorkflow Status   proposed\n\tIs Draft          true\n\tRevisions         1\n\tCurrent Revision  1\n\nRevision 1:\n\tCreated At        1970-05-23T21:21:18+00:00\n
```rust
        let display = "\
Version 1:
	Workflow Status   proposed
	Is Draft          true
	Revisions         1
	Current Revision  1

Revision 1:
	Created At        1970-05-23T21:21:18+00:00
	Submitter         0200ef9ab9243baee54f61a64d66aeb1d33bb063f16dfaa72e61886b9870c2b7ee

<tag></tag>";
```

2021-11-04 18:32 UTC, leebradley commented on cli/src/actions/purchase_orders.rs
> +        let display = "Purchase Order PO-00000-0000:\n\tBuyer Org         test\n\tSeller Org        test2\n\tWorkflow Status   created\n\tCreated At        1970-05-23T21:21:17+00:00\n\tClosed
```rust
        let display = "\
Purchase Order PO-00000-0000:
	Buyer Org         test
	Seller Org        test2
	Workflow Status   created
	Created At        1970-05-23T21:21:17+00:00
	Closed            false

Version 1:
	Workflow Status   proposed
	Is Draft          true
	Revisions         1
	Current Revision  1

Revision 1:
	Created At        1970-05-23T21:21:18+00:00
	Submitter         0200ef9ab9243baee54f61a64d66aeb1d33bb063f16dfaa72e61886b9870c2b7ee

<tag></tag>";
```

2021-11-04 18:32 UTC, leebradley commented on cli/man/grid-po-show.1.md
>  Revision 4:
@dnewh Ah I could see how that was confusing. I was commenting on this revision, and when I said "same with the revision output below" I meant the other command ouput on this manpage that also features Revisions (so line 117 and 145 with the current set of changes)

2021-11-04 18:52 UTC, leebradley submitted a review, later dismissed

2021-11-04 21:38 UTC, shannynalayna submitted a review, later dismissed

2021-11-04 21:47 UTC, vaporos requested changes

2021-11-04 21:47 UTC, vaporos commented on cli/Cargo.toml
> +grid-sdk = { path = "../sdk", features = ["postgres", "sqlite", "pike", "schema", "product", "product-gdsn", "purchase-order", "location", "client", "client-reqwest", "data-validation"] }
Several of these features, including the new purchase-order being added, shouldn't _always_ be pulled in from the grid-sdk. This would cause purchase-order (which is experimental) to always be pulled into the CLI even when compiled without purchase-order (such as when default or stable).

2021-11-04 21:49 UTC, vaporos commented on cli/Cargo.toml
> +chrono = "0.4.19"
Only use the most significant digits - "0.4" in this case.

This should also only be pulled in when PO is enabled.

2021-11-04 22:06 UTC, vaporos approved these changes

2021-11-05 14:18 UTC, leebradley approved these changes

2021-11-05 14:19 UTC, shannynalayna approved these changes

2021-11-05 15:23 UTC, merged