Update `add` method in state to consider updates
hyperledger/grid pull request #1016
Opened 2021-11-03 20:18 UTC by shannynalayna

This change updates the `add_purchase_order_version` method in the
purchase order state module to consider if a purchase order version is
being updated. This means, when the po is fetched from state, the method
will now check to see if a version with the same ID exists in the list
and then it is removed and re-inserted with the updated version.
Otherwise, a new version is simply added to the end of the purchase
order's `versions` list.

Signed-off-by: Shannyn Telander <telander@bitwise.io>

2021-11-03 21:09 UTC, dnewh requested changes

2021-11-03 21:09 UTC, dnewh commented on contracts/purchase_order/src/state.rs
> +        let mut vers_index = None;
Like @leebradley mentioned, this could use `.position` to avoid making it mutable

2021-11-03 21:58 UTC, shannynalayna commented on contracts/purchase_order/src/state.rs
> +        let mut vers_index = None;
Alright I updated that part to use position

2021-11-04 14:00 UTC, leebradley approved these changes

2021-11-04 14:13 UTC, dnewh approved these changes

2021-11-04 21:39 UTC, agunde406 approved these changes

2021-11-04 21:43 UTC, merged