Support `alternate_id` for PO creation and lookup
hyperledger/grid pull request #1030
Opened 2021-11-08 20:42 UTC by dnewh

This updates the Grid PO store, SDE, and CLI to support PO creation and lookup using a properly formatted (`<id_type>:<id>`) alternate ID. This change includes an update to the `grid create po` CLI command to update the flag for specifying an alternate ID to `--alternate-id` from the less descriptive `--id`.

2021-11-10 23:44 UTC, leebradley requested changes
Tested locally. One minor change, otherwise LGTM.

2021-11-10 23:44 UTC, leebradley commented on cli/man/grid-po-create.1.md
> -`--id`
We should update the example on line 86 to also use `--alternate-id`.

2021-11-11 17:29 UTC, dnewh commented on cli/man/grid-po-create.1.md
> -`--id`
updated

2021-11-11 22:33 UTC, leebradley approved these changes

2021-11-12 22:07 UTC, shannynalayna approved these changes
Tested

2021-11-15 17:08 UTC, agunde406 approved these changes

2021-11-15 17:09 UTC, merged