Clean up client feature
hyperledger/grid pull request #1034
Opened 2021-11-10 18:26 UTC by dnewh

This PR contains several updates to the client module. These changes are intended to work towards stabilizing the `client` feature. Changes include:
 - Standardizing documentation
 - Standardizing objects to derive the same traits where applicable
 - Removing the `create_client_factory` fn in favor of creating the factories directly
 - Reorganizing the client module to group like files and simplify config

2021-11-11 14:26 UTC, shannynalayna commented on sdk/src/client/purchase_order/reqwest.rs
> +/// The Reqwest implementation of the Location client
s/location/Purchase Order

2021-11-11 14:33 UTC, shannynalayna commented on sdk/src/client/schema/reqwest.rs
> +/// The Reqwest implementation of the Location client
s/location/Schema

2021-11-11 14:33 UTC, shannynalayna commented on sdk/src/client/purchase_order/reqwest.rs
> +/// The Reqwest implementation of the Location client
s/location/Purchase Order

2021-11-11 14:33 UTC, shannynalayna commented on sdk/src/client/product/reqwest.rs
> +/// The Reqwest implementation of the Location client
s/ Location / Product

2021-11-11 14:33 UTC, shannynalayna commented on sdk/src/client/pike/reqwest.rs
> +/// The Reqwest implementation of the Location client
s / Location / Pike

2021-11-11 14:33 UTC, shannynalayna commented on sdk/src/client/purchase_order.rs
> +    /// * `service_id` - optional service id if running splinter
Should / Could these updates to the comments go into the first commit ? Also, this `service_id` description doesn't match the ones from that commit

2021-11-11 16:27 UTC, shannynalayna submitted a review, later dismissed
lgtm

2021-11-11 20:36 UTC, leebradley requested changes

2021-11-11 20:36 UTC, leebradley commented on sdk/src/client/reqwest/purchase_order/mod.rs
Listing purchase order alternate ids is still unimplemented (line 268)

2021-11-11 22:29 UTC, leebradley approved these changes

2021-11-12 19:40 UTC, agunde406 approved these changes

2021-11-12 21:17 UTC, shannynalayna approved these changes

2021-11-12 21:17 UTC, merged