Enforce uniqueness for PO alternate IDs
hyperledger/grid pull request #1068
Opened 2021-11-16 18:31 UTC by dnewh

This updates the purchase order code to enforce uniqueness for alternate IDs. This adds checks to both the client and PO store to make sure that alternate IDs are only used once per splinter circuit or sawtooth instance.

2021-11-16 23:34 UTC, leebradley requested changes

2021-11-16 23:34 UTC, leebradley commented on sdk/src/client/reqwest/purchase_order/mod.rs
> +        )?;
```rust
let dto_vec = fetch_entities_list::<data::PurchaseOrder>(
    &self.url,
    PO_ROUTE.to_string(),
    service_id,
    None,
)?;
```

We're indexing the server purchase orders as though we expect a large dataset. I don't think it makes sense to fetch that entire dataset in the client, and then iterate over items client-side multiple times to do unique id constraint checks.

There are a couple of alternatives to this, such as making a server endpoint that will return a list of purchase orders by a list of ids (this could possibly be implemented merely as a filter on the list po endpoint with a comma-delimited list of ids). We pass all the alternate ids to that endpoint. If the dataset is empty, the client can be reasonably sure the unique constraint is not violated.

Which kind of brings me to another thought, that `check_alternate_ids_are_unique` is maybe too specific a client function and could be replaced by something more generic like listing purchase orders by a list of ids.

2021-11-18 14:58 UTC, shannynalayna commented on sdk/src/purchase_order/store/diesel/schema.rs
> +    purchase_order_alternate_id (alternate_id_type, alternate_id, service_id) {
Curious how this operates with a sawtooth backend, does it just not include that value in the composite key if service id is none ?

2021-11-18 21:02 UTC, dnewh commented on sdk/src/purchase_order/store/diesel/schema.rs
> +    purchase_order_alternate_id (alternate_id_type, alternate_id, service_id) {
yeah, that table still has the service_id column but the value is always `None` or however the db handles that value

2021-11-19 16:30 UTC, dnewh commented on sdk/src/client/reqwest/purchase_order/mod.rs
> +        )?;
updated to do the check in the cli/store

2021-11-19 16:30 UTC, dnewh commented on sdk/src/client/reqwest/purchase_order/mod.rs
> +    ) -> Result<bool, ClientError> {
updated

2021-11-19 21:53 UTC, leebradley approved these changes
Tested locally. LGTM!

2021-11-19 21:53 UTC, leebradley commented on sdk/src/purchase_order/store/diesel/operations/list_purchase_orders.rs
> +                        |id| match get_uid_from_alternate_id::pg::get_uid_from_alternate_id(
We might want to change this in the future to avoid SQL queries within loops, but TBH this specific call is unlikely to become a performance issue unless we pass a very large number of alternate ids.

2021-11-22 16:22 UTC, shannynalayna requested changes
Looks like this happens when running on Sawtooth: 
```
gridd-alpha                        | ERROR [gridd::event] An error occurred while handling events: Event Error: null value in column "service_id" of relation "purchase_order_alternate_id" violates not-null constraint
```

So, in the case that service id field is null (sawtooth) this error occurs... wonder if we could do a conditional id for sawtooth v splinter

2021-11-22 17:45 UTC, dnewh commented
> Looks like this happens when running on Sawtooth:
> 
> ```
> gridd-alpha                        | ERROR [gridd::event] An error occurred while handling events: Event Error: null value in column "service_id" of relation "purchase_order_alternate_id" violates not-null constraint
> ```
> 
> So, in the case that service id field is null (sawtooth) this error occurs... wonder if we could do a conditional id for sawtooth v splinter

removed the db check for now. The check in the cli/store operation should suffice

2021-11-22 18:45 UTC, shannynalayna approved these changes
Tested locally and the sawtooth example worked 👍

2021-11-22 21:22 UTC, leebradley approved these changes

2021-11-22 21:27 UTC, vaporos approved these changes

2021-11-22 22:19 UTC, merged