Shannynalayna fix internal errs
hyperledger/grid pull request #1162
Opened 2021-12-02 19:09 UTC by shannynalayna

2021-12-02 19:11 UTC, dnewh approved these changes

2021-12-06 15:13 UTC, dnewh approved these changes

2021-12-13 21:33 UTC, CLEckhardt approved these changes
Tested and worked for me.

2021-12-14 17:05 UTC, dnewh approved these changes

2021-12-15 14:51 UTC, vaporos requested changes

2021-12-15 14:51 UTC, vaporos commented on contracts/purchase_order/src/handler.rs
> +                .ok_or_else(|| {
These changes appear correct, but the reasoning given in the commit message is incorrect.

Returning an "InternalError" from a transaction means that the processing of the transaction was non-deterministic as some unexpected (system-level) error occurred. It is a signal to Splinter/Sawtooth to retry the transaction later, hoping the issue is resolved. Resolutions of this type of error would include system resource issues (tried to read state but the database was down) or deploying a new version of the smart contract (because it was buggy). Actual errors like this are expected to be extremely rare when processing smart contracts.

An "InvalidTransaction" means "the transaction that was submitted was not valid". So, for example, if an workflow state is given that doesn't exist, that is an "InvalidTransaction" because processing it is inconsistent with the list of built-in workflows available. Importantly, this is not actually an error as it is normal operation for a smart contract to determine if a transaction is valid or invalid.

2021-12-15 18:14 UTC, shannynalayna commented on contracts/purchase_order/src/handler.rs
> +                .ok_or_else(|| {
Updated the first commit message to better explain what's going on there

2021-12-15 18:16 UTC, leebradley approved these changes

2021-12-16 16:46 UTC, dnewh approved these changes

2021-12-16 18:43 UTC, CLEckhardt approved these changes

2021-12-16 21:43 UTC, vaporos approved these changes

2021-12-17 13:23 UTC, merged