Stabilization updates for `workflow`
hyperledger/grid pull request #1172
Opened 2021-12-08 18:45 UTC by shannynalayna

This adds a few more stabilization updates, including beefed up module lvl and rustdoc comments and an update to the `can_transition` method.

2021-12-08 19:14 UTC, leebradley submitted a review, later dismissed

2021-12-09 22:19 UTC, dnewh requested changes

2021-12-09 22:19 UTC, dnewh commented on sdk/src/workflow/subworkflow.rs
> +    /// Retreive a specific workflow state from this subworkflow. Returns `None` if the state
s/retreive/retrieve

2021-12-10 22:13 UTC, shannynalayna commented on sdk/src/workflow/subworkflow.rs
> +    /// Retreive a specific workflow state from this subworkflow. Returns `None` if the state
Updated!

2021-12-13 18:12 UTC, dnewh approved these changes

2021-12-13 18:12 UTC, leebradley approved these changes

2021-12-13 21:21 UTC, agunde406 approved these changes

2021-12-13 22:02 UTC, merged