Update "update po" action in po smart contract
hyperledger/grid pull request #1213
Opened 2021-12-30 15:04 UTC by shannynalayna

Updates the "update_purchase_order" method to handle a list of versions. This also updates the method to correctly handle versions depending on the intended update state. This also updates the related tests.

2022-01-12 17:44 UTC, dnewh approved these changes
tested

2022-01-12 17:53 UTC, CLEckhardt submitted a review, later dismissed
Tested

2022-01-13 14:25 UTC, vaporos requested changes

2022-01-13 14:25 UTC, vaporos commented on contracts/purchase_order/src/handler.rs
> +                    .with_workflow_state("accepted".to_string())
The smart contract should not know about specific workflow state strings like "accepted".

2022-01-13 16:00 UTC, shannynalayna commented on contracts/purchase_order/src/handler.rs
> +                    .with_workflow_state("accepted".to_string())
Updated to return errors if the smart contract ends up in a place where it finds other versions (besides the one specified in the po's accepted vers num) that are in a state with the `accepted` constraint or if the po's specified accepted version is not in a state with the `accepted` constraint

2022-01-13 20:17 UTC, CLEckhardt approved these changes
Tested

2022-01-13 20:20 UTC, dnewh approved these changes

2022-01-13 21:25 UTC, vaporos approved these changes

2022-01-13 21:25 UTC, merged