Add `xsd-download` CLI command
hyperledger/grid pull request #1252
Opened 2022-01-19 12:44 UTC by leebradley

Add an XSD download CLI command, along with several utility methods for
downloading, extracting, and validating the files within the schema
archive.

Signed-off-by: Lee Bradley <bradley@bitwise.io>

2022-01-21 20:55 UTC, dnewh submitted a review, later dismissed
tested

2022-01-24 16:21 UTC, CLEckhardt requested changes

2022-01-24 16:21 UTC, CLEckhardt commented on cli/src/actions/xsd_downloader/validator.rs
> +    let data = std::fs::read(file).unwrap();
--no-download panics when there isn't an artifact

```
root@gridd-alpha:/usr/share/grid/xsd# grid download-xsd --no-downl│
oad                                                               │
validating hash of /var/lib/grid/artifact/gs1.zip                 │
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` v│
alue: Os { code: 2, kind: NotFound, message: "No such file or dire│
ctory" }', cli/src/actions/xsd_downloader/validator.rs:15:36      │
note: run with `RUST_BACKTRACE=1` environment variable to display │
a backtrace      
```

2022-01-24 16:21 UTC, CLEckhardt commented on cli/src/main.rs
> +                    Arg::with_name("copy_from")
It looks like this should take a value.

2022-01-24 16:21 UTC, CLEckhardt commented on cli/src/main.rs
> +                    Arg::with_name("artifact_dir")
It looks like this should also take a value.

2022-01-25 20:32 UTC, leebradley commented on cli/src/actions/xsd_downloader/validator.rs
> +    let data = std::fs::read(file).unwrap();
Good catch! Fixed

2022-01-25 20:33 UTC, leebradley commented on cli/src/main.rs
> +                    Arg::with_name("copy_from")
Added `takes_value(true)`

2022-01-25 20:33 UTC, leebradley commented on cli/src/main.rs
> +                    Arg::with_name("artifact_dir")
Added `takes_value(true)`

2022-01-26 11:47 UTC, shannynalayna commented on cli/man/grid-download-xsd.1.md
> +  Copyright 2021 Cargill Incorporated
This man page should be copyright for `2022`

2022-01-26 11:55 UTC, shannynalayna commented on cli/src/actions/xsd_downloader/downloader.rs
> +use std::fs::{self, File};
This file is missing a copyright

2022-01-26 12:02 UTC, shannynalayna commented on cli/src/actions/xsd_downloader/extractor.rs
> +use std::fs::{self, File};
Need a copyright

2022-01-26 12:14 UTC, shannynalayna commented on cli/src/actions/xsd_downloader/mod.rs
> +mod downloader;
Copyright :)

2022-01-26 12:24 UTC, shannynalayna commented on cli/src/actions/xsd_downloader/mod.rs
> +mod downloader;
Copyrights need to be added to all the new files, noticed a few more but won't comment everywhere

2022-01-26 12:26 UTC, shannynalayna commented on cli/src/main.rs
> +                        .conflicts_with("no_download")
From the man page, it looks like this option should be usable with `no_download`. The man page should be updated to show these args are not usable together, unless this line is a mistake?

2022-01-26 16:37 UTC, leebradley commented on cli/man/grid-download-xsd.1.md
> +  Copyright 2021 Cargill Incorporated
Updated!

2022-01-26 16:37 UTC, leebradley commented on cli/src/actions/xsd_downloader/downloader.rs
> +use std::fs::{self, File};
Added!

2022-01-26 16:37 UTC, leebradley commented on cli/src/actions/xsd_downloader/extractor.rs
> +use std::fs::{self, File};
Added!

2022-01-26 16:38 UTC, leebradley commented on cli/src/actions/xsd_downloader/mod.rs
> +mod downloader;
Added!

2022-01-26 16:40 UTC, leebradley commented on cli/src/main.rs
> +                        .conflicts_with("no_download")
So actually I'd somehow missed the req that no_download should be compatible with copy_from, so you found a legit bug here. Fixed and added a unit test to validate the functionality.

2022-01-26 17:31 UTC, shannynalayna submitted a review, later dismissed
Tested

2022-01-26 18:54 UTC, CLEckhardt reviewed
Tested and functionality is good. A few notes:
- `--copy-from` without `--no-download` effectively ignores the arg if the filename is incorrect
- `--force` still gives a message “validating hash of ...”
- man page and CLI help should probably say that the file for `--copy-from` needs to be named “gs1.zip”
Still working on testing po actions, running into some unrelated issues, but I'll confirm it all works when that's done

2022-01-26 19:39 UTC, leebradley commented
> * `--copy-from` without `--no-download` effectively ignores the arg if the filename is incorrect

Yeah, I was initially going to be very strict and require all files exist, but there's also the use case @shannynalayna pointed out of only having some of the files available (and downloading the rest). I'm not sure how to best approach this.

> * `--force` still gives a message “validating hash of ...”

By design `--force` still validates the hash of downloaded files, and only ignores the hashes of cached files.

> * man page and CLI help should probably say that the file for `--copy-from` needs to be named “gs1.zip”

Hmm if this is going to be added to docs that means we'll technically be supporting manually tinkering with the internal cache, which tbh I didn't anticipate. I think I'm going to rename this file so it's a little more future-proof.

2022-01-26 19:42 UTC, CLEckhardt commented
Cool, makes sense.

2022-01-26 19:57 UTC, leebradley commented
So in response to the feedback form @CLEckhardt I've made three changes:

1) After consulting a bit, we've decided to support users working with these cache files. Thus I've renamed "gs1.zip" in the cache to "GS1_XML_3-4-1_Publication.zip" so it matches the default filename and will not need renamed in the future if a different version comes out.

2) Added a reference to GS1_XML_3-4-1_Publication.zip in the docs so users are aware what needs to be in the copy directory.

3) Changed a `debug!` message to `info!` so users can immediately see if there are missing files in the cache directory. Example below:

```
root@gridd-alpha:/# grid download-xsd --copy-from foo              
file "GS1_XML_3-4-1_Publication.zip" doesn't exist in copy path
downloading file from https://www.gs1.org/docs/EDI/xml/3.4.1/GS1_XML_3-4-1_Publication.zip
download finished
validating hash of /var/cache/grid/xsd_artifact_cache/GS1_XML_3-4-1_Publication.zip.download
extracting to schema directory
```

2022-01-26 20:16 UTC, shannynalayna commented on cli/man/grid-download-xsd.1.md
> +cahce directory, Grid will not attempt to re-download them, and instead
sp/cahce/cache

2022-01-26 20:21 UTC, leebradley commented on cli/man/grid-download-xsd.1.md
> +cahce directory, Grid will not attempt to re-download them, and instead
Fixed!

2022-01-26 21:24 UTC, shannynalayna approved these changes
Tested; temp file is being removed if the overall download fails

2022-01-26 22:19 UTC, dnewh approved these changes

2022-01-26 22:44 UTC, merged