Shannynalayna add payload infrastructure
hyperledger/grid pull request #1391
Opened 2022-04-21 17:23 UTC by shannynalayna

This adds a v2 to the `submit` module which contains structs used to deserialize REST API JSON requests into smart contract actions. Mainly, this adds the infrastructure needed to create Batches based on Grid's smart contracts.

A few specifics for deserializing: 
- Adds interim `DeserializableXPayload` structs for the Pike and Location modules. These structs assist in determining which action is specified in the JSON. 
- Updates the `CreateAgentAction` to be deserialized from the `CreateAgentActionBuilder`. This allows for errors relating to malformed actions to be more specific as to what is wrong with the payload, rather than attempting to deserialize directly into the `Action` itself. This generates the error from the builder's `build` method, rather than the JSON parsing.
- Adds tests for deserializing multiple JSON objects into the `Payload` enum, to verify the process of converting a list of JSON structs into the correct action.
- Adds tests for deserializing Pike actions for the individual actions and the top-level `Payload` object.

2022-05-03 16:38 UTC, dnewh requested changes

2022-05-03 18:01 UTC, dnewh submitted a review, later dismissed

2022-05-04 22:47 UTC, shannynalayna commented on sdk/src/rest_api/resources/submit/v2/payloads/location.rs
> +    #[serde(default)]
These enable serde to deserialize into this specific action, mostly depending on the fields. Using serde, these are necessary

2022-05-06 20:03 UTC, CLEckhardt requested changes

2022-05-10 15:37 UTC, shannynalayna commented on sdk/src/rest_api/resources/submit/v2/payloads/mod.rs
> +            (Payload::Schema(ex_payload), Payload::Schema(test_payload)) => {
Yes it was, removed now

2022-05-10 16:27 UTC, dnewh approved these changes

2022-05-10 17:57 UTC, leebradley approved these changes

2022-05-10 18:20 UTC, merged