Clean up `BatchTrackingStore` tests
hyperledger/grid pull request #1400
Opened 2022-04-29 18:17 UTC by dnewh

This cleans up the batch tracking store tests by putting repetitive,
    shared code into functions.

2022-05-18 17:31 UTC, leebradley requested changes

2022-05-18 17:31 UTC, leebradley commented on sdk/src/batch_tracking/store/diesel/mod.rs
> +    fn get_tracking_batch(
This function is the only weird one to me, just because the builder pattern is (in part) meant to avoid large number of optional arguments, and we already have a builder.

So right now the function signature is:
```rust
    fn get_tracking_batch(
        batch: Batch,
        submitted: bool,
        timestamp: Option<i64>,
        batch_status: Option<BatchStatus>,
        submission_error: Option<SubmissionError>,
        dcid: Option<String>,
    ) -> TrackingBatch { /* snip */ }
```

Maybe it would be cleaner to do something like this, where you'd just preload the builder with test and required values:

```rust
    fn get_tracking_batch_builder(
        batch: Batch,
        submitted: bool,
    ) -> TrackingBatchBuilder { /* snip */ }
```

2022-05-18 18:17 UTC, dnewh commented on sdk/src/batch_tracking/store/diesel/mod.rs
> +    fn get_tracking_batch(
updated

2022-05-18 18:28 UTC, leebradley approved these changes
LGTM

2022-05-18 19:40 UTC, shannynalayna requested changes
Should update all the `unwrap`s that happen throughout the tests to be `expect`s for easier debugging

2022-05-19 17:16 UTC, shannynalayna approved these changes

2022-05-20 16:56 UTC, merged