Make `TrackingBatch` `service_id` an `Option`
hyperledger/grid pull request #1401
Opened 2022-04-29 19:47 UTC by dnewh

This makes the `service_id` field on the `TrackingBatch` struct an
    `Option`. This is in support of work on the batch queuer.

2022-05-18 17:43 UTC, leebradley requested changes

2022-05-18 17:43 UTC, leebradley commented on sdk/src/batch_tracking/store/diesel/models.rs
> +        let serv_id = if let Some(b) = batch.service_id() {
The `b` isn't a great name, but you could avoid it entirely by using
```rust
let serv_id = batch.service_id().unwrap_or(NON_SPLINTER_SERVICE_ID_DEFAULT);
```

2022-05-18 17:43 UTC, leebradley commented on sdk/src/batch_tracking/store/diesel/models.rs
> +        let mut serv_id = Some(batch.service_id.to_string());
This assignment could all be a single statement without mut

2022-05-19 19:13 UTC, dnewh commented on sdk/src/batch_tracking/store/diesel/models.rs
> +        let serv_id = if let Some(b) = batch.service_id() {
updated

2022-05-19 19:13 UTC, dnewh commented on sdk/src/batch_tracking/store/diesel/models.rs
> +        let mut serv_id = Some(batch.service_id.to_string());
updated

2022-05-19 20:11 UTC, leebradley approved these changes

2022-05-20 16:04 UTC, shannynalayna approved these changes

2022-05-20 16:56 UTC, merged