WIP location cli commands
hyperledger/grid pull request #291
Opened 2020-08-24 15:45 UTC by RyanLassigBanks

Proposed CLI interface for location commands

## grid location 
```
grid-location
Create, update, delete, show, or list locations

USAGE:
    grid location [FLAGS] <SUBCOMMAND>

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      Do not display output
    -V, --version    Prints version information
    -v               Log verbosely

SUBCOMMANDS:
    create    Create locations from a yaml file
    delete    Delete a location
    help      Prints this message or the help of the given subcommand(s)
    list      List currently defined locations
    show      Show location specified by ID argument
    update    Update locations from a yaml file
```
## grid location create
```
grid-location-create
Create locations from a yaml file

USAGE:
    grid location create [FLAGS] <path>

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      Do not display output
    -V, --version    Prints version information
    -v               Log verbosely

ARGS:
    <path>    Path to yaml file containing a list of locations
```
## grid location update
```
Update locations from a yaml file

USAGE:
    grid location update [FLAGS] <path>

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      Do not display output
    -V, --version    Prints version information
    -v               Log verbosely

ARGS:
    <path>    Path to yaml file containing a list of locations
```
## grid location delete
```
grid-location-delete
Delete a location

USAGE:
    grid location delete [FLAGS] <location_id>

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      Do not display output
    -V, --version    Prints version information
    -v               Log verbosely

ARGS:
    <location_id>    Unique ID for a location
```
## grid location show
```
grid-location-show
Show location specified by ID argument

USAGE:
    grid location show [FLAGS] <location_id>

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      Do not display output
    -V, --version    Prints version information
    -v               Log verbosely

ARGS:
    <location_id>    ID of location
```
## grid location list
```
grid-location-list
List currently defined locations

USAGE:
    grid location list [FLAGS]

FLAGS:
    -h, --help       Prints help information
    -q, --quiet      Do not display output
    -V, --version    Prints version information
    -v               Log verbosely
```

2020-09-04 17:53 UTC, dplumb94 approved these changes

2020-09-04 20:36 UTC, vaporos commented on cli/src/main.rs
> +                (@arg namespace: +takes_value conflicts_with[file] "Location name space (example: GS1)")
namespace and owner are currently positional arguments; I suggest making them options --namespace and --owner for example. --namespace can default to GS1 so you never have to actually enter it; --owner so that we could (maybe) have this set in an environment variable or config file in the future.

2020-09-29 18:20 UTC, dnewh requested changes

2020-10-01 20:44 UTC, dnewh requested changes

2020-10-01 20:44 UTC, dnewh commented on cli/src/main.rs
> +    println!("YES HELLO: {:?}", properties);
remove unnecessary print statement

2020-10-14 20:29 UTC, dnewh requested changes

2020-10-14 20:29 UTC, dnewh commented on cli/src/main.rs
> +                let namespace = match m.value_of("namespace").unwrap_or("GS1") {
This should be location_namespace to align with the product format

2020-10-14 20:29 UTC, dnewh commented on cli/src/main.rs
> +            ("udpate", Some(m)) => {
sp udpate/update

2020-10-14 20:29 UTC, dnewh commented on cli/src/actions/locations.rs
> +            Namespace::GS1 => "GS1",
This should be return "gs1_location" to align with the approach taken in product

2020-10-14 20:29 UTC, dnewh commented on cli/src/actions/locations.rs
> +            Namespace::GS1 => "GS1",
"gs1_location" here too

2020-10-20 19:10 UTC, dplumb94 approved these changes

2020-10-20 19:11 UTC, dnewh approved these changes

2020-10-20 19:12 UTC, merged