Add organization store implementation
hyperledger/grid pull request #310
Opened 2020-09-01 20:00 UTC by dnewh

This adds the postgres, sqlite, and in-memory implementations of the organization store following the new pattern. This does not currently integrate the new store into the daemon but that integration will come in a later PR.

2020-09-03 19:35 UTC, RyanLassigBanks requested changes

2020-09-03 19:35 UTC, RyanLassigBanks commented on sdk/src/grid_db/organizations/store/error.rs
> +pub enum OrganizationStoreError {
This has a lot of overlap with CommitStoreError. We should consider having a common error module at the root grid_db

2020-09-03 20:04 UTC, dnewh commented on sdk/src/grid_db/organizations/store/error.rs
> +pub enum OrganizationStoreError {
updated

2020-09-10 17:31 UTC, vaporos requested changes

2020-09-10 17:31 UTC, vaporos commented on sdk/src/grid_db/organizations/store/diesel/operations/add_organizations.rs
> +pub(in crate::grid_db::organizations) trait OrganizationStoreAddOrganizationsOperation {
Seems odd that code at that high level would need this trait. should it be super::super (which is grid_db::oranizations::store::diesel)? (Same comment for other operations.)

2020-09-10 17:31 UTC, vaporos commented on sdk/src/store/sqlite.rs
> +    fn get_grid_organization_store(&self) -> Box<dyn crate::grid_db::OrganizationStore> {
This feels like its in the wrong commit as its not sqlite-specific.

2020-09-10 18:10 UTC, dnewh commented on sdk/src/store/sqlite.rs
> +    fn get_grid_organization_store(&self) -> Box<dyn crate::grid_db::OrganizationStore> {
This is part of the implementation of StoreFactory for SqliteStoreFactory

2020-09-10 18:14 UTC, dnewh commented on sdk/src/grid_db/organizations/store/diesel/operations/add_organizations.rs
> +pub(in crate::grid_db::organizations) trait OrganizationStoreAddOrganizationsOperation {
updated

2020-09-10 18:36 UTC, vaporos submitted a review, later dismissed

2020-09-10 19:26 UTC, dplumb94 requested changes

2020-09-10 19:26 UTC, dplumb94 commented on sdk/src/hex.rs
> +
I think we need full rustdocs for these functions since its part of the Grid SDK

2020-09-10 19:26 UTC, dplumb94 commented on sdk/src/grid_db/organizations/store/memory.rs
> +///Implementation of OrganizationStore that stores Commits in memory. Useful for when
Just a typo in the comment... Commits should be lowercase unless its referring to an actual object

2020-09-11 14:21 UTC, vaporos commented on sdk/src/grid_db/organizations/store/memory.rs
> +///Implementation of OrganizationStore that stores Commits in memory. Useful for when
There should be a space after /// as well.

2020-09-11 14:42 UTC, dnewh commented on sdk/src/hex.rs
> +
Added

2020-09-11 14:42 UTC, dnewh commented on sdk/src/grid_db/organizations/store/memory.rs
> +///Implementation of OrganizationStore that stores Commits in memory. Useful for when
Updated

2020-09-11 20:02 UTC, dplumb94 approved these changes

2020-09-11 20:24 UTC, vaporos approved these changes

2020-09-11 20:28 UTC, RyanLassigBanks approved these changes

2020-09-11 20:29 UTC, merged