Add location store
hyperledger/grid pull request #319
Opened 2020-09-08 21:55 UTC by dnewh

This adds the postgres and sqlite store implementations and stubs the in-memory implementation (to make it compile) for the location store following the new pattern. This does not currently integrate the new store into the daemon but that integration will come in a later PR.

2020-09-08 21:55 UTC, dnewh commented
This is built on top of PR #310

2020-09-11 21:56 UTC, dplumb94 commented on sdk/src/store/memory.rs
> +    fn get_grid_location_store(&self) -> Box<dyn LocationStore> {
Is there any reason for stubbing out this implementation but implementing it for organizations?

2020-09-11 22:02 UTC, vaporos approved these changes

2020-09-11 22:02 UTC, dnewh commented on sdk/src/store/memory.rs
> +    fn get_grid_location_store(&self) -> Box<dyn LocationStore> {
The organizations and commits stores were done before we decided to not implement the in-memory stores. The memory module will be deleted in a later PR

2020-09-11 22:10 UTC, vaporos requested changes

2020-09-11 22:10 UTC, vaporos commented on sdk/src/grid_db/locations/store/mod.rs
> +#[cfg(feature = "diesel")]
Diesel implementation should be entirely under diesel:: and shouldn't change the definition of the store API.

2020-09-11 22:39 UTC, dnewh commented on sdk/src/grid_db/locations/store/mod.rs
> +#[cfg(feature = "diesel")]
updated

2020-09-14 18:21 UTC, vaporos commented on sdk/src/grid_db/locations/store/diesel/mod.rs
> +#[cfg(feature = "diesel")]
This is unnecessary (another below this), as the top-level module already has the feature check

2020-09-14 18:43 UTC, vaporos approved these changes

2020-09-15 19:22 UTC, dplumb94 approved these changes

2020-09-15 22:08 UTC, merged