Schema Store
hyperledger/grid pull request #320
Opened 2020-09-09 18:15 UTC by RyanLassigBanks

Add schema store triat, and postgres, sqlite, and hasmap implementations

2020-09-09 19:03 UTC, chenette commented
The PR description's meaning is clear, but corrections now would be helpful when creating the next release notes. My recommendation: "Add schema store trait and PostgreSQL, SQLite, and hashmap implementations"

P.S. If "hashmap" means a specific language's HashMap (like Rust?), then s/hashmap/HashMap/.

2020-09-11 21:52 UTC, dplumb94 approved these changes

2020-09-14 14:03 UTC, dnewh approved these changes

2020-09-14 14:03 UTC, dnewh commented on sdk/src/grid_db/schemas/store/mod.rs
> +    fn add_schema(&self, schema: &Schema) -> Result<(), SchemaStoreError>;
I think these should have rustdocs similar to the other modules

2020-09-14 15:02 UTC, dnewh approved these changes

2020-09-14 18:41 UTC, dnewh approved these changes

2020-09-14 19:14 UTC, vaporos commented on sdk/src/grid_db/schemas/store/mod.rs
> +impl Into<(NewGridSchema, Vec<NewGridPropertyDefinition>)> for &Schema {
Move this into diesel::

2020-09-15 19:24 UTC, dplumb94 submitted a review, later dismissed

2020-09-17 13:45 UTC, vaporos submitted a review, later dismissed

2020-09-17 15:52 UTC, dnewh requested changes

2020-09-17 15:52 UTC, dnewh commented on sdk/src/grid_db/schemas/error.rs
> +#[cfg(feature = "diesel")]
I think these should be in diesel

2020-09-17 18:48 UTC, RyanLassigBanks commented on sdk/src/grid_db/schemas/error.rs
> +#[cfg(feature = "diesel")]
Updatd

2020-09-17 18:53 UTC, dnewh submitted a review, later dismissed

2020-09-17 19:03 UTC, dplumb94 approved these changes

2020-09-17 20:24 UTC, vaporos approved these changes

2020-09-17 20:24 UTC, merged