Product Stores
hyperledger/grid pull request #323
Opened 2020-09-11 21:15 UTC by RyanLassigBanks

Adds ProductStore traits and two implementations. One for Postgresql and one Sqlite.

2020-09-11 22:07 UTC, vaporos requested changes

2020-09-11 22:07 UTC, vaporos commented on sdk/src/grid_db/products/store/mod.rs
> +#[cfg(feature = "diesel")]
The diesel feature should be entirely under the product::diesel module. We should not be exposing diesel-specific APIs just because diesel is enabled.

2020-09-14 13:21 UTC, RyanLassigBanks commented on sdk/src/grid_db/products/store/mod.rs
> +#[cfg(feature = "diesel")]
Could you elaborate on how you would like this set up? The commit store also uses the diesel feature flag in it's [store/mod.rs](https://github.com/hyperledger/grid/blob/9a8c0926904470242df79da291f978b6258e1833/sdk/src/grid_db/commits/store/mod.rs#L124) so I'm sure what issue is.

2020-09-14 19:22 UTC, vaporos requested changes

2020-09-14 19:22 UTC, vaporos commented on sdk/src/grid_db/products/store/diesel/mod.rs
> +#[cfg(feature = "diesel")]
This feature guard should be unnecessary here.

2020-09-15 19:29 UTC, dplumb94 submitted a review, later dismissed

2020-09-17 13:47 UTC, vaporos approved these changes

2020-09-17 18:48 UTC, dplumb94 approved these changes

2020-09-17 18:49 UTC, merged