Add agent store
hyperledger/grid pull request #324
Opened 2020-09-11 21:25 UTC by dnewh

This adds the postgres and sqlite store implementations and stubs the in-memory implementation (to make it compile) for the agent store following the new pattern. This does not currently integrate the new store into the daemon but that integration will come in a later PR.

2020-09-11 22:12 UTC, vaporos requested changes

2020-09-11 22:12 UTC, vaporos commented on sdk/src/grid_db/agents/store/mod.rs
> +#[cfg(feature = "diesel")]
Diesel implementation should be under store::diesel and shouldn't change the store API when enabled.

2020-09-11 23:11 UTC, dnewh commented on sdk/src/grid_db/agents/store/mod.rs
> +#[cfg(feature = "diesel")]
updated

2020-09-17 15:28 UTC, RyanLassigBanks commented on sdk/src/grid_db/agents/store/error.rs
> +#[cfg(feature = "diesel")]
Should these also be in the diesel module?

2020-09-17 15:39 UTC, RyanLassigBanks submitted a review, later dismissed

2020-09-17 15:50 UTC, dnewh commented on sdk/src/grid_db/agents/store/error.rs
> +#[cfg(feature = "diesel")]
updated

2020-09-17 15:52 UTC, RyanLassigBanks approved these changes

2020-09-17 18:36 UTC, dplumb94 approved these changes

2020-09-17 18:43 UTC, vaporos approved these changes

2020-09-17 18:53 UTC, merged