Update product CLI
hyperledger/grid pull request #354
Opened 2020-09-29 19:21 UTC by dnewh

This updates the product CLI create, update, and delete subcommands. This includes enabling users to add/update single products by passing the required values via command line options rather than using a YAML file. Additionally, the `--path` option is now the `--file, -f` option and can take either a file path or a URL. This PR also updates the format of a valid product YAML file to simplify properties. The format of a property is now `<property_name>: <property_value>` rather than having to provide the `name`, `type`, and `value` separately.

2020-10-08 16:21 UTC, dplumb94 requested changes
Please update examples/splinter/README.md to include the new format in the product.yaml example

2020-10-08 20:58 UTC, dplumb94 commented
getting a CLI error:

```root@gridd-alpha:/# cat > product.yaml 
   - product_namespace: "GS1"
     product_id: "013600000929"
     owner: "314156"
     properties:
       product_name: "Truvia 80 ct."
       image_url:
        "https://target.scene7.com/is/image/Target/GUEST_b7a6e983-b391-40a5-ad89-2f906bce5743?fmt=png&wid=1400&qlt=80"
       brand_name: "Truvia"
       product_description: "Truvia Sugar 80CT"
       gpc: 30016951
       net_content: "80CT"
       target_market: 840
^C
root@gridd-alpha:/# grid -k alpha-agent product create  product.yaml
Error: Field brand_name not found```

2020-10-09 17:55 UTC, dplumb94 approved these changes
tested

2020-10-14 14:13 UTC, RyanLassigBanks approved these changes

2020-10-14 14:24 UTC, dplumb94 approved these changes

2020-10-14 14:26 UTC, merged