Add gridd man page
hyperledger/grid pull request #361
Opened 2020-10-06 18:32 UTC by dnewh

This adds a man page for the gridd command.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2020-10-08 14:55 UTC, rbuysse requested changes

2020-10-08 14:55 UTC, rbuysse commented on daemon/man/gridd.1.md
> +will connect to a Sqtooth backend. The connection URL can be configured using
s/Sqtooth/Sawtooth

2020-10-08 14:55 UTC, rbuysse commented on daemon/man/gridd.1.md
> +=======
Can you resort this list in alphabetical order?

2020-10-13 19:31 UTC, RyanLassigBanks approved these changes

2020-10-13 19:38 UTC, rbuysse approved these changes

2020-10-13 20:01 UTC, merged