Add location schema
hyperledger/grid pull request #366
Opened 2020-10-12 20:36 UTC by RyanLassigBanks

Fields included in location schema were sourced from [this document](https://wiki.hyperledger.org/download/attachments/9110626/GLN%20Overview%20for%20GRID.pdf?api=v2)
Signed-off-by: Ryan Banks <rbanks@bitwise.io>

2020-10-12 21:01 UTC, dnewh submitted a review, later dismissed

2020-10-13 20:19 UTC, dnewh approved these changes

2020-10-14 20:06 UTC, dnewh approved these changes

2020-10-14 20:45 UTC, dnewh requested changes

2020-10-14 20:45 UTC, dnewh commented on cli/schemas/location.yaml
> +    - name: conactName
sp conact/contact

2020-10-19 16:19 UTC, dnewh submitted a review, later dismissed

2020-11-05 19:54 UTC, dplumb94 requested changes

2020-11-05 19:54 UTC, dplumb94 commented on cli/schemas/location.yaml
> +        Provider, Supplier, 3rdParty, Warhouse, IndependentOperator, Operator]
Warhouse -> Warehouse I assume

2020-11-06 18:31 UTC, dplumb94 approved these changes

2020-11-06 18:31 UTC, vaporos approved these changes

2020-11-06 21:22 UTC, merged