Add initial product schema yaml file
hyperledger/grid pull request #374
Opened 2020-10-13 20:13 UTC by RyanLassigBanks

Signed-off-by: Ryan Banks <rbanks@bitwise.io>

2020-10-14 13:58 UTC, dnewh approved these changes

2020-10-19 19:22 UTC, dnewh requested changes

2020-10-21 15:50 UTC, dplumb94 approved these changes

2020-10-22 16:56 UTC, rbuysse requested changes

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        Measurement Rules. If the packaging dimensions is for a platform or
s/is/are

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        Measurement Rules. If the packaging dimensions is for a platform or
s/is/are

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        "A free text field specifying the serving size for which the nutrient
Is this meant to have quotes around it?

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +      description: What is the color of the package? E.g. Green or White
Can this be re-written as a statement? This is the only description posed as a question.

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        "A free text field specifying the serving size for which the nutrient
Is this meant to have quotes around it?

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        Measurement Rules. If the packaging dimensions is for a platform or
There's a subject-verb disagreement here.

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        Measurement Rules. If the packaging dimensions is for a platform or
Subject-verb disagreement

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        Words or phrases that enables web search engines to find trade items on
Subject-verb disagreement.

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +        the internet for example Shampoo, Lather, Baby.
colon after example

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +    - name: "features_and_benefits_list"
Is this meant to have quotes around it?

2020-10-22 16:56 UTC, rbuysse commented on cli/schemas/product.yaml
> +      description: "The geographic area where an activity has taken place."
Is this meant to have quotes around it?

2020-10-27 16:18 UTC, rbuysse submitted a review, later dismissed

2020-10-27 16:29 UTC, vaporos requested changes
Need better attribution.

2020-10-28 19:25 UTC, vaporos submitted a review, later dismissed

2020-10-28 20:41 UTC, dplumb94 submitted a review, later dismissed

2021-02-10 15:53 UTC, closed without merging

2021-02-10 15:53 UTC, RyanLassigBanks commented
We've decided to take the product schema in a different direction that makes this PR obsolete