Add version headers
hyperledger/grid pull request #400
Opened 2020-10-27 18:23 UTC by dnewh

This adds protocol version headers to client and UI requests. This is currently not checked but will be in the future so this is a forward-compatibility change.

2020-11-04 17:57 UTC, vaporos requested changes

2020-11-04 17:57 UTC, vaporos commented on cli/src/http.rs
> +        .header("GridProtocolVersion", "0.1")
This should be "1" instead of "0.1".

2020-11-04 18:41 UTC, dnewh commented on cli/src/http.rs
> +        .header("GridProtocolVersion", "0.1")
updated

2020-11-18 20:31 UTC, vaporos approved these changes

2020-11-20 15:31 UTC, dplumb94 approved these changes

2020-11-20 15:50 UTC, merged