Fix global CLI options
hyperledger/grid pull request #415
Opened 2020-10-28 17:03 UTC by dnewh

This moves the key and service-id args one level deeper. These args were previously global to all grid commands but were not relevant to keygen and admin subcommands. Now these args must be specified after the grid subcommand rather than the grid command and are only available on relevant subcommands. This also updates the Grid-on-Splinter example README to reflect these changes.

2020-11-05 21:17 UTC, dplumb94 requested changes
This should include the --wait to only show for creation commands and --url only for commands that have to do with the REST API.

2020-11-23 16:57 UTC, dplumb94 submitted a review, later dismissed

2020-11-24 19:59 UTC, peterschwarz commented on cli/src/main.rs
> +            (@arg key: -k +takes_value "base name for private key file")
Isn't the key command only relevant to the commands that also have `wait`? I.e. both are related to submitting transactions.

2020-11-24 20:01 UTC, dnewh commented on cli/src/main.rs
> +            (@arg key: -k +takes_value "base name for private key file")
I believe you also need it for fetching records unlike wait

2020-11-24 20:21 UTC, peterschwarz commented on cli/src/main.rs
> +            (@arg key: -k +takes_value "base name for private key file")
That does not look to be the case

2020-11-24 22:48 UTC, dnewh commented on cli/src/main.rs
> +            (@arg key: -k +takes_value "base name for private key file")
updated

2020-11-25 16:11 UTC, peterschwarz approved these changes

2020-11-25 16:22 UTC, dplumb94 approved these changes

2020-11-25 17:10 UTC, merged