Update schema list output
hyperledger/grid pull request #423
Opened 2020-11-02 22:24 UTC by dnewh

This updates the `grid schema list` command's output to display a
subset of the schema data in a table format. This improves readability
and enables the use of other command line utilities for searching and
filtering results.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2020-11-09 13:56 UTC, RyanLassigBanks submitted a review, later dismissed

2020-11-16 21:58 UTC, RyanLassigBanks approved these changes

2020-11-17 20:02 UTC, dplumb94 requested changes

2020-11-17 20:02 UTC, dplumb94 commented on cli/src/actions/schemas.rs
> +    // // Maximum length of the name column
Extra comment string

2020-11-17 20:04 UTC, dnewh commented on cli/src/actions/schemas.rs
> +    // // Maximum length of the name column
updated

2020-11-18 18:17 UTC, dplumb94 approved these changes

2020-11-18 19:30 UTC, RyanLassigBanks approved these changes

2020-11-18 20:33 UTC, merged