Overhaul Grid REST API spec
hyperledger/grid pull request #433
Opened 2020-11-12 18:53 UTC by dplumb94

This commit is a heavy edit of the Grid REST API specification. The
specification was outdated and had many structural and consistency
issues. Due to the scope of changes, the spec was rewritten from scratch
but pulls in some models and structure from the previous version as
appropriate.

In summary, the following changes were made:
 - Updated the info object
 - Added documentation and links to transaction routes
 - Standardized summary and description format
 - Removed inaccurate error types
 - Organized schemas and paths by feature

Signed-off-by: Darian Plumb <dplumb@bitwise.io>

2020-11-16 22:16 UTC, dnewh requested changes

2020-11-16 22:16 UTC, dnewh commented on daemon/openapi.yaml
> +        description: A binary encoded protobuf BatchList.
No period needed, not a sentence. There are a few other places that have the same thing

2020-11-16 22:27 UTC, dnewh approved these changes

2020-11-16 22:27 UTC, RyanLassigBanks approved these changes

2020-11-16 22:28 UTC, dnewh submitted a review, later dismissed

2020-11-17 19:48 UTC, dnewh approved these changes

2020-11-17 20:21 UTC, RyanLassigBanks approved these changes

2020-11-17 20:41 UTC, merged