Include record owner in has_permission check
hyperledger/grid pull request #510
Opened 2021-01-29 18:06 UTC by dplumb94

Updates the has_permission check to include `record_owner`, which is the Pike ID of the org that owns the record that we are checking permissions for.  This also adds a check to make sure the agent actually belongs to that org and removes it from the smart contract. This is part of an effort to move common code from the contracts to the SDK.

2021-02-01 16:45 UTC, dnewh submitted a review, later dismissed

2021-02-03 15:09 UTC, dnewh approved these changes

2021-02-03 19:03 UTC, peterschwarz requested changes

2021-02-03 19:03 UTC, peterschwarz commented on contracts/product/src/state.rs
> -    pub fn get_agent(&self, public_key: &str) -> Result<Option<Agent>, ApplyError> {
Likewise, it would be good to explain why these are removed.  If they are removed based on no longer being used, move the removal to a separate commit.

2021-02-04 21:56 UTC, dplumb94 commented on contracts/product/src/state.rs
> -    pub fn get_agent(&self, public_key: &str) -> Result<Option<Agent>, ApplyError> {
Updated the commit messages to explain the removal of unit tests

2021-02-08 16:59 UTC, peterschwarz approved these changes

2021-02-08 17:04 UTC, dnewh approved these changes

2021-02-09 13:40 UTC, merged