Consolidate pike db modules
hyperledger/grid pull request #516
Opened 2021-02-04 18:34 UTC by dnewh

This consolidates the agents and organizations db modules into one "pike" module. The functionality doesn't change at all but now all the pike operations are in one place. This simplifies some code and also makes it clearer that these modules are for the Pike smart contract. This also removes the unused memory store implementation for organizations. This was the last module with a memory backed store implementation so this module was removed from the library.

2021-02-09 21:54 UTC, RyanLassigBanks submitted a review, later dismissed

2021-02-10 23:08 UTC, vaporos requested changes

2021-02-10 23:08 UTC, vaporos commented on sdk/src/store/mod.rs
> +        #[cfg(not(feature = "sqlite"))]
Why would this be special for sqlite and not postgres? But also, isn't the match statement complete without this block?

The error message in the block doesn't give any clues about what actually happened.

2021-02-11 16:09 UTC, dnewh commented on sdk/src/store/mod.rs
> +        #[cfg(not(feature = "sqlite"))]
updated to check for both features and to have a more descriptive error message

2021-02-11 17:33 UTC, dnewh commented on sdk/src/store/mod.rs
> +        #[cfg(not(feature = "sqlite"))]
Removing the block completely was causing errors for at least some combinations of features

2021-02-19 20:26 UTC, RyanLassigBanks approved these changes

2021-02-19 21:03 UTC, vaporos approved these changes

2021-02-19 21:04 UTC, merged