Update Pike db module tables
hyperledger/grid pull request #521
Opened 2021-02-08 19:54 UTC by dnewh

This updates the Pike DB module with updated/new tables in preparation for the Pike 2.0 update. This adds some tables that are not used quite yet but are defined in the Identity RFC. This also includes the associated migrations for postgres and sqlite backends and relevant daemon/cli updates.

2021-02-11 19:35 UTC, peterschwarz requested changes

2021-02-11 19:35 UTC, peterschwarz commented on sdk/src/hex.rs
> -pub fn as_hex<S>(data: &[u8], serializer: S) -> Result<S::Ok, S::Error>
Looks like these should be part of the hex commit

2021-02-11 19:35 UTC, peterschwarz commented on daemon/src/rest_api/routes/organizations.rs
> +// use serde_json::Value as JsonValue;
Commented code, here and below

2021-02-22 14:56 UTC, RyanLassigBanks approved these changes

2021-02-22 14:59 UTC, peterschwarz commented on sdk/src/pike/store/diesel/operations/fetch_organization.rs
> +        self.conn.immediate_transaction::<_, PikeStoreError, _>(|| {
Why the use of `immediate_transaction` instead of just `transaction`?

2021-02-22 15:42 UTC, dnewh commented on sdk/src/pike/store/diesel/operations/fetch_organization.rs
> +        self.conn.immediate_transaction::<_, PikeStoreError, _>(|| {
This was just how all the operations in Grid were written. Updated now

2021-02-22 15:46 UTC, peterschwarz approved these changes

2021-02-22 15:55 UTC, RyanLassigBanks approved these changes

2021-02-22 17:12 UTC, merged