Add Pike 2.0 create and update
hyperledger/grid pull request #531
Opened 2021-02-15 23:04 UTC by dnewh

This adds functionality for creating and updating roles along with other Pike 2.0 updates. This includes significant updates to the Pike db store/SDE, the Pike smart contract and any smart contract that uses Pike, the Grid REST API, and the Grid CLI.

2021-03-03 16:59 UTC, dplumb94 commented on sdk/protos/pike_payload.proto
> +  repeated AlternateID alternate_ids = 4;
skipped a number here

2021-03-03 17:00 UTC, dplumb94 commented on sdk/protos/pike_state.proto
> +message Role {
These can be numbered in order since we arent worried about backward compatibility

2021-03-03 17:35 UTC, dplumb94 commented on sdk/src/permissions.rs
> +    const ROLE_ALPHA_INSPECTOR: &str = "Inspector";
It looks like the prefixes were removed from these consts. I would recommend either not using the variables for these tests or keeping the prefix if using them as external roles. I think that just removing the prefixes makes the tests a bit confusing. Also in some places the org ID consts are not being used.

2021-03-03 17:37 UTC, dplumb94 commented on sdk/src/permissions.rs
> +                    return Err(PermissionCheckerError::InvalidRole("External roles need to be prefixed with their org ID. Format: <org_id>.<role_name>".to_string()));
Hmm this is interesting, so for `inherits_from` we are still using the dot-separated role names. Maybe that's fine but it makes me think it should be a struct or something. Not blocking for this but probably needs some discussion before we release a version of Grid with this in it.

2021-03-03 17:52 UTC, dnewh commented on sdk/src/permissions.rs
> +                    return Err(PermissionCheckerError::InvalidRole("External roles need to be prefixed with their org ID. Format: <org_id>.<role_name>".to_string()));
it is only dot separated for external roles, similar to how adding an external role to an agent would work. Internal roles can still be referenced just by the role name

2021-03-03 17:57 UTC, dplumb94 requested changes
Getting an error trying to view roles via CLI:

```
root@gridd-alpha:/# grid role create --permissions schema::can-create-schema,product::can-create-product crgl ProductOwner 'role to create products' -v
...
root@gridd-alpha:/# grid role show crgl ProductOwner
missing field `allowed_orgs` at line 1 column 223
```

2021-03-03 18:15 UTC, dnewh commented on sdk/src/permissions.rs
> +    const ROLE_ALPHA_INSPECTOR: &str = "Inspector";
I disagree with this. I think having the consts as the role names potentially makes the tests easier to maintain down the line and having them without the prefix and adding that on for external roles reflects how people would actually use that.

2021-03-05 20:57 UTC, dplumb94 approved these changes
Tested, works. I kind of feel like we should wrap this stuff in a feature. At the very least we need to go through the stabilization process for it before the next grid release.

2021-03-05 21:42 UTC, RyanLassigBanks approved these changes

2021-03-06 00:37 UTC, merged