Added libzmq3-dev as a dependency
hyperledger/grid pull request #552
Opened 2021-02-23 02:35 UTC by saki-osive

The build needs the `libzmq3-dev` package on Debian(Ubuntu). This PR addresses this.

2021-03-17 18:45 UTC, dplumb94 requested changes

2021-03-17 18:45 UTC, dplumb94 commented on README.md
> +Before building, make sure you `libzmq3-dev` package installed in Debian(Ubuntu).
Hey looks like you have a typo: "make sure you `libzmq3-dev`" -> "make sure you have the `libzmq3-dev`". Also you should probably update the commit message to indicate that this is only in the scope of Ubuntu. 

If you are able, you could add the command for the osx environment as well. Otherwise that could be added in a later commit.

Thanks for the contribution!

2021-03-23 02:40 UTC, saki-osive commented on README.md
> +Before building, make sure you `libzmq3-dev` package installed in Debian(Ubuntu).
Sure, I'll see and add, thanks @dplumb94

2021-05-26 19:09 UTC, dplumb94 requested changes
Hey @saki-osive,
Since these three commits are all essentially the same change, please squash them into one commit. Also, you will need to add a signoff to the commit. If you click the "details" link by where that check failed below the conversations, it has some instructions for doing that. Once you've done that, go ahead and re-request my review and we will get the PR reviewed ASAP.

2021-09-06 16:10 UTC, saki-osive commented
@dplumb94 Please review it.

2021-09-09 18:55 UTC, shannynalayna requested changes
Hi @saki-osive 👋  
Please squash that second commit into the first "Added libzmq3-dev as a dependency" commit. 
Also, as @dplumb94 suggested, please add more description to this commit message to indicate this change is only within the scope of ubuntu.

2021-09-13 12:08 UTC, saki-osive commented
I cannot see why it can't be build in the Jenkins log, I'm closing this and creating a few one

2021-09-13 12:08 UTC, closed without merging