Move grid rest api code into SDK
hyperledger/grid pull request #559
Opened 2021-03-04 19:57 UTC by RyanLassigBanks

2021-03-11 14:35 UTC, vaporos commented on sdk/src/lib.rs
> +#[cfg(all(feature = "rest-api-resources", feature = "pike"))]
Another way to guard these extern crate statements is by the crate itself -- #[cfg(feature = "serde_json")]

2021-03-11 14:37 UTC, vaporos commented on sdk/src/rest_api/resources/agents/v1/handler.rs
> +                println!("FETCH AGENT ERROR {:?}", err);
This should be removed (or debug!())

2021-03-11 14:39 UTC, vaporos commented on sdk/src/rest_api/resources/agents/v1/mod.rs
> +pub use payloads::*;
No wildcards in use statements please.

2021-03-11 14:48 UTC, vaporos requested changes
Since this isn't a diff against the existing code (something a careful sequence of commits could provide), please detail the list of changes done against the daemon version of the code to get to this point so when we manually compare to the existing code we have a guide of the changes we are looking for.

2021-03-19 15:54 UTC, dplumb94 approved these changes

2021-03-19 16:42 UTC, vaporos approved these changes

2021-03-19 19:56 UTC, RyanLassigBanks commented on sdk/src/rest_api/resources/locations/v1/payloads.rs
> +#[derive(Debug, Serialize, Deserialize)]
Integration tests deserialize and inspect these payloads

2021-03-19 20:11 UTC, RyanLassigBanks commented on sdk/Cargo.toml
> +reqwest = { version = "0.10.1", features = ["json", "blocking"], optional = true }
Removed blocking feature

2021-03-22 19:57 UTC, vaporos approved these changes

2021-03-22 20:02 UTC, dplumb94 approved these changes

2021-03-22 20:03 UTC, merged