Add alternate ID support
hyperledger/grid pull request #572
Opened 2021-03-15 15:08 UTC by dnewh

This adds alternate ID support to the Pike, Product, and Location smart contracts. This replaces the functionality of the special case of organization metadata that was being checked for GS1 company prefixes with a more flexible field on the Organization object. This field can be used for any number of alternate identifiers for an organization.

2021-03-15 21:15 UTC, RyanLassigBanks approved these changes

2021-03-16 15:45 UTC, dplumb94 requested changes

2021-03-16 15:45 UTC, dplumb94 commented on contracts/location/src/handler.rs
> +        if alternate_id.id_type() == "gs1_company_prefixes"
This should really be "gs1_company_prefix". Each org may have several of these but the key of the ID itself should be "gs1_company_prefix"

2021-03-16 15:45 UTC, dplumb94 commented on contracts/location/src/handler.rs
> +            "Organization {} does not have the correct gs1 alternate ID",
This can still say "prefix" because the actual ID type is a GS1 company prefix.

2021-03-16 15:45 UTC, dplumb94 commented on contracts/product/src/handler.rs
> +                    "The agents organization does not have the gs1_company_prefixes alternate ID: {:?}",
same as location comment

2021-03-17 17:07 UTC, RyanLassigBanks approved these changes

2021-03-18 17:07 UTC, dplumb94 approved these changes

2021-03-18 17:09 UTC, merged