Add clap code for `grid po` subcommand
hyperledger/grid pull request #595
Opened 2021-03-25 14:16 UTC by shannynalayna

This change adds the Clap code to add the `po` subcommand to the Grid
CLI. This initial subcommand includes the `list`, `show`, `create`, and
`update` subcommands.

Signed-off-by: Shannyn Telander <telander@bitwise.io>

2021-03-25 16:23 UTC, RyanLassigBanks submitted a review, later dismissed

2021-03-25 16:37 UTC, RyanLassigBanks submitted a review, later dismissed

2021-03-25 18:00 UTC, vaporos requested changes

2021-03-25 19:09 UTC, RyanLassigBanks approved these changes

2021-03-25 20:02 UTC, peterschwarz commented on cli/src/main.rs
> +                                .long("rm-id")
This isn't consistent with the `add-id` option this is `alternate_id_type`, the other is `alternate_id`

2021-03-25 20:07 UTC, RyanLassigBanks approved these changes

2021-03-26 15:46 UTC, vaporos approved these changes

2021-03-26 15:47 UTC, merged