PO workflows
hyperledger/grid pull request #602
Opened 2021-03-25 19:06 UTC by RyanLassigBanks

Initial workflow for purchase order smart contract

2021-03-25 20:41 UTC, vaporos requested changes

2021-03-25 20:41 UTC, vaporos commented on contracts/purchase_order/src/workflow.rs
> +    let mut buyer = PermissionAlias::new("po.buyer");
You need to define different buyer and sellers per-state, because the permissions differ per-state. For example, 'Issued' has 3 permissions and 'Confirmed' has 2 permissions.

2021-03-25 20:41 UTC, vaporos commented on contracts/purchase_order/src/workflow.rs
> +    buyer.add_transition("issued");
The states should be capitalized--"Issued" here--because these would potentially be shown the end-users in the CLI or pulldowns.

2021-03-25 20:41 UTC, vaporos commented on contracts/purchase_order/src/workflow.rs
> +pub fn po_workflow() -> Workflow {
We should differentiate this constructor function from the one we will have that includes the collab. sub-workflow.

2021-03-29 15:35 UTC, vaporos commented on contracts/purchase_order/src/workflow.rs
> +    SubWorkflowBuilder::new("system-of-record-subworkflow")
This should be "po".

2021-03-29 15:36 UTC, vaporos commented on contracts/purchase_order/src/workflow.rs
> +    SubWorkflowBuilder::new("collaborative-subworkflow")
Should be "verison"

2021-03-29 15:36 UTC, vaporos commented on contracts/purchase_order/src/workflow.rs
> +    SubWorkflowBuilder::new("po-subworkflow")
Should be "po"

2021-03-29 15:42 UTC, vaporos submitted a review, later dismissed

2021-03-29 15:46 UTC, peterschwarz submitted a review, later dismissed

2021-03-30 13:40 UTC, vaporos commented
What changed?

2021-03-30 14:05 UTC, RyanLassigBanks commented
Fixed lint

2021-04-01 16:52 UTC, peterschwarz approved these changes

2021-04-19 22:18 UTC, vaporos approved these changes

2021-04-26 15:56 UTC, merged