Add po list command man page
hyperledger/grid pull request #605
Opened 2021-03-25 19:54 UTC by peterschwarz

This change adds the man page for listing purchase orders.  It also adds the base man page for `grid po`.

2021-03-25 20:07 UTC, RyanLassigBanks requested changes

2021-03-25 20:07 UTC, RyanLassigBanks commented on cli/man/grid-po-list.1.md
> +  output
Should probably end with period like flag descriptions above

2021-03-25 20:07 UTC, RyanLassigBanks commented on cli/man/grid-po-list.1.md
> +`--service-id`
These statements should probably all end in periods.

2021-03-25 20:07 UTC, RyanLassigBanks commented on cli/man/grid-po-list.1.md
> +: Specifies service ID if `--service-id` is not used
Should probably end in a period

2021-03-25 20:17 UTC, peterschwarz commented on cli/man/grid-po-list.1.md
> +  output
This is based on the existing man pages, so  the problem might actually be the periods else where

2021-03-25 20:32 UTC, RyanLassigBanks approved these changes

2021-03-26 15:03 UTC, jsmitchell requested changes

2021-03-26 15:03 UTC, jsmitchell commented on cli/man/grid-po-list.1.md
> +: Optionally, Filter the purchase orders for the organization specified by
s/Filter/filter/

2021-03-26 15:03 UTC, jsmitchell commented on cli/man/grid-po-list.1.md
> +  `ORG_ID`.  Does *not* use the `GRID_ORG_ID` environment variable.
s/Does/This does/

2021-03-26 15:03 UTC, jsmitchell commented on cli/man/grid-po-list.1.md
> +: Specifies the output format of the list. (default `human`). Possible values
s/(default 'human')//. Add "Defaults to 'human'." at the end.

2021-03-26 15:03 UTC, jsmitchell commented on cli/man/grid-po-list.1.md
> +will display all of the purchase orders that have an accepted version and is
s/and is/and are/

2021-03-26 15:18 UTC, peterschwarz commented on cli/man/grid-po-list.1.md
> +: Optionally, Filter the purchase orders for the organization specified by
Fixed

2021-03-26 15:18 UTC, peterschwarz commented on cli/man/grid-po-list.1.md
> +  `ORG_ID`.  Does *not* use the `GRID_ORG_ID` environment variable.
Fixed

2021-03-26 15:19 UTC, peterschwarz commented on cli/man/grid-po-list.1.md
> +: Specifies the output format of the list. (default `human`). Possible values
Updated and moved to end

2021-03-26 15:19 UTC, peterschwarz commented on cli/man/grid-po-list.1.md
> +will display all of the purchase orders that have an accepted version and is
fixed

2021-03-26 15:26 UTC, RyanLassigBanks approved these changes

2021-03-26 15:34 UTC, RyanLassigBanks approved these changes

2021-03-26 15:38 UTC, jsmitchell approved these changes

2021-03-26 15:57 UTC, merged