Implement Fetch and List purchase order routes
hyperledger/grid pull request #625
Opened 2021-03-29 21:18 UTC by dplumb94

2021-03-29 21:28 UTC, dnewh requested changes

2021-03-29 21:28 UTC, dnewh commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +<<<<<<< HEAD
looks like some merge conflicts got committed

2021-03-29 21:28 UTC, dnewh commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +<<<<<<< HEAD
here too

2021-03-30 15:27 UTC, dplumb94 commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +<<<<<<< HEAD
fixed

2021-03-30 15:27 UTC, dplumb94 commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +<<<<<<< HEAD
forgot to save file before committing it heh

2021-03-31 19:17 UTC, dnewh submitted a review, later dismissed

2021-04-08 19:45 UTC, vaporos commented on sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
> +            uuid: purchase_order.uuid.clone(),
Are these clone() needed here since purchase_order is consumed?

2021-04-13 16:07 UTC, dplumb94 commented on sdk/src/rest_api/resources/purchase_order/v1/payloads.rs
> +            uuid: purchase_order.uuid.clone(),
They were not necessary. Updated.

2021-04-14 22:29 UTC, vaporos approved these changes

2021-04-16 14:53 UTC, dnewh approved these changes

2021-04-16 15:21 UTC, merged