Implement create product using XML data
hyperledger/grid pull request #629
Opened 2021-04-02 21:02 UTC by dplumb94

This is the first PR to implement XML support for product. The code was getting a bit complex so I am submitting this one first to keep it incremental. Remaining tasks include:

- Implementing update
- Validation
- Fetching alternate ID to fill in the owner

To test: 

1. start up the `examples/splinter/docker-compose.yaml` network and create a Grid circuit between alpha and beta
2. Set up agents and organizations as follows:

```
grid keygen alpha-agent

export GRID_SERVICE_ID=<circuit ID>::gsAA

grid organization create crgl Cargill --metadata gs1_company_prefixes=0
grid role create crgl productowner --permissions schema::can-create-schema,product::can-create-product --active
grid agent update crgl $(cat ~/.grid/keys/alpha-agent.pub) --active --role productowner --role admin
```
3. submit a transaction to create a schema with the new `xsd_schema.yaml` file. If you are executing this from the gridd-alpha container you might need to copy it in. 
`$ grid schema create xsd-schema.yaml`
4. Create a product using some example XML data that conforms to the GridTradeItems XSD.
`$ grid product create -f yourproduct.yaml`

2021-04-08 20:02 UTC, vaporos requested changes

2021-04-08 20:02 UTC, vaporos commented on cli/src/main.rs
> +                    let key = m
We should create a Grid CLI variant of https://github.com/Cargill/splinter/blob/main/cli/src/signing.rs so these key options work properly.

2021-04-12 20:13 UTC, RyanLassigBanks approved these changes
Tested locally

2021-04-13 17:58 UTC, dplumb94 commented on cli/src/main.rs
> +                            Arg::with_name("xml")
I think another option here would be to name the argument `--gdsn-3-1` (which could correspond with a more descriptive property name of the resulting Grid product definition). I think if we make it completely dynamic we could end up with some strange edge cases with duplicate GTIN product definitions being submitted etc. The complexity in solving that might not be proportional to the actual usefulness of the feature.

2021-04-14 20:29 UTC, dplumb94 commented on cli/src/main.rs
> +                    let key = m
What isnt working properly? I can create a story for that

2021-04-14 22:40 UTC, vaporos commented on sdk/Cargo.toml
> +    "product-gdsn"
This should be in alphabetical order after pike-rest-api

2021-04-14 22:42 UTC, vaporos commented on sdk/Cargo.toml
> +product-gdsn = [
These should all be in alphabetical order as well (all features after experimental (experimental being special so separate)).

2021-04-14 23:34 UTC, vaporos requested changes

2021-04-14 23:34 UTC, vaporos commented on cli/src/main.rs
> +                        .arg(
This should be behind a feature

2021-04-14 23:34 UTC, vaporos commented on cli/src/main.rs
> +                            Arg::with_name("xml")
"--gdsn-3-1" would work but its less user-friendly as it should be easy to determine which type of file it is at runtime, with just --file arguments.

2021-04-14 23:34 UTC, vaporos commented on cli/src/main.rs
> +                    let key = m
The first is the approach to looking up and handling the key argument, which should follow what is done in the splinter CLI, using code similar to that linked above; the second piece is creating a signer early and not passing the key into functions (pass the signer instead). splinter CLI has many examples of this.

2021-04-16 16:15 UTC, vaporos commented on cli/Cargo.toml
> +    "sqlite"
Add the , back to this line pls

2021-04-16 16:24 UTC, vaporos approved these changes

2021-04-16 17:37 UTC, dnewh approved these changes

2021-04-16 18:28 UTC, merged