Fix UI sidebar
hyperledger/grid pull request #635
Opened 2021-04-06 21:54 UTC by dnewh

This fixes the sidebar for the grid UI to correctly show icons for the
different saplings. This change depends on the PR to splinter-canopyjs:
https://github.com/Cargill/splinter-canopyjs/pull/21.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-04-12 18:43 UTC, dplumb94 requested changes
Instead of this and the related change in the Splinter admin UI, we can use material icon that goes with each sapling. That way we can ensure that all of the sapling icons have a similar look to them.

2021-04-13 14:17 UTC, dnewh commented
> Instead of this and the related change in the Splinter admin UI, we can use material icon that goes with each sapling. That way we can ensure that all of the sapling icons have a similar look to them.

This is still an option. This is just additional functionality

2021-04-21 16:26 UTC, dplumb94 approved these changes

2021-04-21 16:27 UTC, RyanLassigBanks approved these changes

2021-04-21 16:28 UTC, merged