Refactor grid daemon splinter module
hyperledger/grid pull request #638
Opened 2021-04-13 19:05 UTC by RyanLassigBanks

Various updates to address comments relating to `splinter-support` feature stabilization

2021-05-04 17:04 UTC, dplumb94 submitted a review, later dismissed

2021-05-10 14:37 UTC, vaporos requested changes

2021-05-10 14:37 UTC, vaporos commented on daemon/src/splinter/event/mod.rs
> + * Copyright 2021 Cargill Incorporated
Was 2019-2021 intended here?

2021-05-10 14:37 UTC, vaporos commented on sdk/src/lib.rs
> +pub mod hex;
Grid SDK is not a hex library, and should not export hex conversion functions.

Because the use case here is "hex::to_hex(signer.public_key());", this can be fixed with converting it to cylinder which allows signer.public_key().as_hex().

2021-05-11 18:53 UTC, RyanLassigBanks commented on sdk/src/lib.rs
> +pub mod hex;
Dropped this commit

2021-05-12 19:41 UTC, vaporos approved these changes

2021-05-18 20:40 UTC, dplumb94 approved these changes

2021-05-19 16:28 UTC, merged