Update Products Table page
hyperledger/grid pull request #649
Opened 2021-04-21 17:03 UTC by dnewh

This updates the ProductsTable component per the updated designs for the Product sapling. This uses the other new/updated components. This page now contains a table  that displays products for a chosen service. This table is filterable and product xml files can be downloaded directly from the table.

## Testing

 - Start the splinter example docker containers and run through creating a circuit and adding product to that circuit
 - in a separate terminal navigate to the `ui/grid-ui` directory and run `npm i` and `npm run start`
 - in a separate terminal navigate to the `ui/saplings/product` directory and run `npm i` and `npm run watch`
 - in a browser, navigate to `localhost:3030`, sign in, go to the product sapling

2021-04-30 20:38 UTC, RyanLassigBanks submitted a review, later dismissed

2021-05-03 17:29 UTC, dplumb94 commented on ui/saplings/product/src/components/CircuitDropdown.js
> +const CircuitDropdown = ({
Can you update the Update CircuitDropdown component commut message to include more context? It looks to be doing more than updating the theme.

2021-05-03 18:20 UTC, dplumb94 requested changes
Getting an error in the table upon switching to the circuit where I have a product: 
```
product.js:55 TypeError: Cannot read property 'TRADEITEM' of undefined
    at Object.p [as accessor] (product.js:85)
    at e (product.js:78)
    at product.js:78
    at Array.forEach (<anonymous>)
    at se (product.js:78)
    at product.js:78
    at Object.da [as useMemo] (product.js:55)
    at Object.t.useMemo (product.js:47)
    at e.useTable (product.js:78)
    at mo (product.js:85)
es @ product.js:55
product.js:85 Error listing products: TypeError: Cannot read property 'TRADEITEM' of undefined
```

2021-05-03 18:20 UTC, dplumb94 commented on examples/splinter/docker-compose.yaml
> +      - "3033:80"
This is not working for me. When I navigate to localhost:3033 I get a blank screen with some errors in the console.

2021-05-07 19:47 UTC, dplumb94 requested changes

2021-05-07 19:47 UTC, dplumb94 commented on ui/saplings/product/src/components/ProductsTable.js
> +              <button className="btn-primary" onClick={handleAddFilter} type="button">Add Filter</button>
It looks like the styling of this text is off. In figma it is Arial Bold 14pt and rendered it is Roboto 16pt.

2021-05-07 19:47 UTC, dplumb94 commented on ui/saplings/product/src/components/CircuitDropdown.js
> +const CircuitDropdown = ({
It looks like the circuitdropdown and filter dropdown icon placements are a bit off from the design. Also we should be using a custom dropdown list instead of the browser default.

2021-05-07 19:47 UTC, dplumb94 commented on ui/saplings/product/src/styles/colors.scss
> +$color-primary: rgb(243, 95, 25) !default;
Why do we need  `!default` here? It seems like we shouldn't expect them to change

2021-05-07 19:47 UTC, dplumb94 commented on ui/saplings/product/src/components/Table.js
> +  const downloadXML = row => {
Does the XML library used here offer any way to format the XML before downloading? Also Im thinking the downloaded version should probably be wrapped in the gridTradeItems element

2021-05-07 19:47 UTC, dplumb94 commented on ui/saplings/product/src/components/Table.scss
> +  table {
Nitpick but it looks like the styling of the table header and row lines ends like 1 px before the container.
![Screen Shot 2021-05-07 at 2 38 24 PM](https://user-images.githubusercontent.com/27690938/117500200-e97dc180-af41-11eb-8f5a-e0ba9bd29519.png)

2021-05-07 19:47 UTC, dplumb94 commented on ui/saplings/product/src/components/ProductsTable.js
> +        Cell: props => <img src={props.value} alt={`${props.row.values.gtin} thumbnail`} className="product-image" />
I think the alt image would be fine without the "GTIN thumbnail". For products without an image it is clear what the image placeholder is without that text.

2021-05-07 19:47 UTC, dplumb94 commented on ui/saplings/product/src/components/Table.js
> +        <span className="label">Rows per page: </span>
I think the rows per page should be configurable. I realize that the design doesnt include a dropdown or anything for it but 10 is not very many if you're looking at it on a desktop sized monitor

2021-05-07 20:09 UTC, dnewh commented on ui/saplings/product/src/components/ProductsTable.js
> +        Cell: props => <img src={props.value} alt={`${props.row.values.gtin} thumbnail`} className="product-image" />
All images should have alt text. This is for basic accessibility

2021-05-10 20:17 UTC, dnewh commented on ui/saplings/product/src/components/Table.scss
> +  table {
I wasn't able to replicate this

2021-05-10 21:34 UTC, dnewh commented on ui/saplings/product/src/styles/colors.scss
> +$color-primary: rgb(243, 95, 25) !default;
this was a holdover from the "style library". Since we're not doing this anymore this was removed

2021-05-10 21:34 UTC, dnewh commented on ui/saplings/product/src/components/Table.js
> +  const downloadXML = row => {
switched to a different library that supports this

2021-05-17 17:33 UTC, dplumb94 approved these changes

2021-05-17 19:15 UTC, RyanLassigBanks approved these changes

2021-05-17 19:19 UTC, merged