Add cross-cutting db features
hyperledger/grid pull request #650
Opened 2021-04-22 19:34 UTC by dnewh

This adds cross-cutting features to the Grid SDK for the locations, products, and schemas modules. These features control whether the db code for each module gets compiled.

2021-04-30 14:58 UTC, RyanLassigBanks approved these changes

2021-05-14 17:14 UTC, vaporos requested changes

2021-05-14 17:14 UTC, vaporos commented on sdk/Cargo.toml
> +location-store-postgres = []
This should depend on "postgresql" and similarly the line below should depend on "sqlite".

2021-05-14 17:14 UTC, vaporos commented on sdk/src/locations/mod.rs
> +    feature = "diesel",
diesel should be implied by the other two features; see comment on Cargo.toml. This comment applies to all other instances as well.

2021-05-14 17:14 UTC, vaporos commented on sdk/Cargo.toml
> +location-store-postgres = []
same for product and schema

2021-05-19 19:06 UTC, RyanLassigBanks approved these changes

2021-05-19 22:36 UTC, vaporos approved these changes

2021-05-20 14:07 UTC, merged