Add date create field to rest api resources
hyperledger/grid pull request #655
Opened 2021-04-29 21:05 UTC by RyanLassigBanks

Adds database generated date create timestamp to agent, role, organization, product, location, and schema endpoints.

Example:

```
GET /agent/021bab739fce4133204c8c0bd939d48e4d32e5b29eb87ed871d2666fcd3f51bb3e
{
  "public_key": "021bab739fce4133204c8c0bd939d48e4d32e5b29eb87ed871d2666fcd3f51bb3e",
  "org_id": "crg",
  "active": true,
  "roles": [
    "admin"
  ],
  "metadata": {},
  "date_created": 1619707637
}
```

2021-04-30 21:45 UTC, dnewh reviewed
tested and it works, just had the comment regarding the migrations

2021-04-30 21:45 UTC, dnewh commented on sdk/src/migrations/diesel/sqlite/migrations/2021-04-23-151946_add_timestamp/down.sql
> +CREATE TABLE pike_agent (
Could these be ALTER TABLE commands rather than DROPping and CREATEing?

2021-05-03 13:37 UTC, RyanLassigBanks commented on sdk/src/migrations/diesel/sqlite/migrations/2021-04-23-151946_add_timestamp/down.sql
> +CREATE TABLE pike_agent (
You can't use ALTER TABLE with DEFAULT CURRENT_TIMESTAMP in sqlite. You get this error 
```
Schema Error: Error: SQLITE_ERROR: Cannot add a column with non-constant default
```
Unfortunately, the only way around it is to recreate the table.

2021-05-03 14:05 UTC, dnewh submitted a review, later dismissed

2021-05-04 18:52 UTC, RyanLassigBanks commented
> DROP/CREATE approach here will delete data in existing installs.

We also take this approach for the pike 2 migration, and we can't add the date created field to the sqlite tables using ALTER TABLE (see my response to @dnewh). Do you know of an alternative solution?

2021-05-05 17:49 UTC, dplumb94 approved these changes

2021-05-05 18:02 UTC, vaporos commented
> We also take this approach for the pike 2 migration...

That was an explicit decision to drop backward compatibility for Pike 1 and the upgrade path will need to be documented/tested in the release notes.

2021-05-05 18:05 UTC, vaporos commented on sdk/src/migrations/diesel/sqlite/migrations/2021-04-23-151946_add_timestamp/down.sql
> +CREATE TABLE pike_agent (
IIRC, its pretty common to create a table then copy the data to the new table, rename, etc.

Perhaps remove this default and use a trigger anyway, allowing this column to be NULL for existing data.

2021-05-05 19:19 UTC, peterschwarz commented on sdk/src/migrations/diesel/sqlite/migrations/2021-04-23-151946_add_timestamp/down.sql
> +CREATE TABLE pike_agent (
This isn't used for dates, but the fundamental principle applies: https://github.com/Cargill/splinter/blob/main/libsplinter/src/migrations/diesel/sqlite/migrations/2021-02-09-042200_update-identity-enum/up.sql

2021-05-07 19:51 UTC, dplumb94 requested changes
`Add date_created field to gridd endpoints` commit message should be updated since that field has a different name now

2021-05-14 17:21 UTC, dnewh approved these changes

2021-05-18 20:39 UTC, dplumb94 approved these changes

2021-05-19 19:03 UTC, merged