Rename `fetch_` operations to `get_`
hyperledger/grid pull request #656
Opened 2021-05-03 16:19 UTC by dnewh

This renames the `fetch_` operations to `get_` operations. This brings
the Grid data store operation in line with the naming conventions used
in Splinter. This is part of stabilizing the postgres and sqlite features.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-05-07 20:01 UTC, dplumb94 reviewed
I get that this is how they are named in Splinter but I don't think it is ideal. Fetch and List correspond nicely to the URI functions whereas Get seems to be overloaded with the HTTP method name.  My 2 cents.

2021-05-17 20:46 UTC, dnewh commented
> I get that this is how they are named in Splinter but I don't think it is ideal. Fetch and List correspond nicely to the URI functions whereas Get seems to be overloaded with the HTTP method name. My 2 cents.

We've discussed this a couple times now. I think the decision was to rename to `get_*`

2021-05-18 19:51 UTC, agunde406 approved these changes

2021-05-19 18:54 UTC, RyanLassigBanks requested changes
I was under the impression that this change was only to pertain to the store functions, which I also disagree with changing, but have begrudgingly accepted.

2021-05-20 14:54 UTC, RyanLassigBanks approved these changes

2021-05-20 14:54 UTC, merged