Make all operations atomic
hyperledger/grid pull request #658
Opened 2021-05-03 16:27 UTC by dnewh

This makes all operations atomic. Previously, this was done in a sort of
piecemeal fashion. This just cleans this up and makes sure all
operations are wrapped in the generic diesel transaction. This is
available for all Diesel backends that implement Diesel::Connection.
This depends on PR #656.

2021-05-03 17:10 UTC, dnewh commented
This depends on PR #656

2021-05-03 19:08 UTC, RyanLassigBanks commented
Will this PR need to be rebased once [656](https://github.com/hyperledger/grid/pull/656) is approved?

2021-05-03 19:18 UTC, dnewh commented
> Will this PR need to be rebased once [656](https://github.com/hyperledger/grid/pull/656) is approved?

yes

2021-05-20 18:26 UTC, agunde406 requested changes

2021-05-20 18:26 UTC, agunde406 commented on sdk/src/batches/store/diesel/operations/list_batches_with_status.rs
> +// Copyright 2018-2021 Cargill Incorporated
Is this a new file? should this be in a different commit?

2021-05-20 18:26 UTC, agunde406 commented on sdk/src/commits/store/error.rs
> +#[cfg(feature = "diesel")]
These changes look like they are unrelated to the commit, should they be in a different commit?

2021-05-20 19:27 UTC, dnewh commented on sdk/src/commits/store/error.rs
> +#[cfg(feature = "diesel")]
These are necessary to make the commitStore operations atomic

2021-05-20 19:51 UTC, agunde406 approved these changes

2021-05-21 20:07 UTC, dplumb94 approved these changes

2021-05-21 20:50 UTC, merged