Update product man pages
hyperledger/grid pull request #684
Opened 2021-05-10 17:27 UTC by RyanLassigBanks

Add explaination of `--xml` option for `grid product create` man page

Remove `--owner` option from `grid product update` man page

Signed-off-by: Ryan Banks <rbanks@bitwise.io>

2021-05-17 17:56 UTC, dplumb94 commented on cli/man/grid-product-create.md
> +`--xml, -x`
the XML arg is removed in this PR: https://github.com/hyperledger/grid/pull/690/commits

2021-05-19 17:03 UTC, RyanLassigBanks commented on cli/man/grid-product-create.md
> +`--xml, -x`
Updated --file explanation to match explanation in pull 690

2021-05-19 17:18 UTC, dnewh approved these changes

2021-05-20 14:37 UTC, KevinAnsleyJohnson approved these changes
LGTM

2021-05-26 15:36 UTC, dplumb94 requested changes
Need to update the "update" command as it also takes other file types. We should add an example using XML but that can be a separate PR.

2021-06-03 17:10 UTC, dplumb94 approved these changes

2021-06-03 18:55 UTC, merged