List and show agents in the CLI
hyperledger/grid pull request #692
Opened 2021-05-14 17:42 UTC by KevinAnsleyJohnson

Includes man-pages. List includes formatting human and csv types, along
with the ability to list roles on their own lines. The Show command
gives additional information, and requires a public key as the
identifier. (Agent ID is synonymous with public key.)

2021-05-19 17:23 UTC, RyanLassigBanks commented
about for agent subcommand should be updated to reference list and how
https://github.com/hyperledger/grid/blob/5541e3518a583d269b90eeba520bc984babc1610/cli/src/main.rs#L156

2021-05-19 17:47 UTC, KevinAnsleyJohnson commented
> about for agent subcommand should be updated to reference list and show
> https://github.com/hyperledger/grid/blob/5541e3518a583d269b90eeba520bc984babc1610/cli/src/main.rs#L156

good catch! however, this also is the case for many other commands as well. I may make a separate PR and fix them all, but for now I will update the current one to reflect the correct fix.

2021-05-19 18:10 UTC, RyanLassigBanks requested changes

2021-05-19 18:10 UTC, RyanLassigBanks commented on cli/src/actions/agents.rs
> +    pub service_id: String,
`service_id` should be `Option<String>` since the service_id` will only be present if running in splinter mode. If grid is connect to a sawtooth network the cli will fail to deserialize this payload as the api will not return a `service_id`

2021-05-19 19:12 UTC, KevinAnsleyJohnson commented on cli/src/actions/agents.rs
> +    pub service_id: String,
Thanks! Also, since service_id is only for splinter, I think it makes sense to remove it from the `show` option as well, otherwise there would be inconsistency. PR is now updated reflecting the Options<String> change, as well as removing the line that prints the Service ID in `show`.

2021-05-19 20:13 UTC, dplumb94 approved these changes
Tested, LGTM.

sample output for other reviewers:

```
MacBook-Pro:grid dplumb$ grid agent list
PUBLIC_KEY                                                         ORG_ID ACTIVE ROLES                                                  
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   productowner, admin, role1, role2, role3, role4, role5 
MacBook-Pro:grid dplumb$ grid agent list --line-per-role
PUBLIC_KEY                                                         ORG_ID ACTIVE ROLE         
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   productowner 
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   admin        
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   role1        
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   role2        
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   role3        
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   role4        
02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778 crgl   true   role5        
MacBook-Pro:grid dplumb$ grid agent list --format=csv
"PUBLIC_KEY","ORG_ID","ACTIVE","ROLES"
"02583654747f593243a7d8635397cc8bbdd25540d26ae1e4318dd99141a03aa778","crgl","true","productowner, admin, role1, role2, role3, role4, role5"
MacBook-Pro:grid dplumb$ grid agent list --format=asdf
error: 'asdf' isn't a valid value for '--format <format>'
        [possible values: csv, human]


USAGE:
    grid agent list --format <format>
```

2021-05-20 13:28 UTC, RyanLassigBanks approved these changes
Tested locally

2021-05-20 14:22 UTC, merged