Refactor pike protocol payload
hyperledger/grid pull request #697
Opened 2021-05-18 16:27 UTC by RyanLassigBanks

PikePayload protocol object now has a single action object instead of
multiple payload objects. The Action enum has been updated to hold a
payload object that corresponds to each enum type.

Signed-off-by: Ryan Banks <rbanks@bitwise.io>

2021-05-18 19:56 UTC, agunde406 requested changes

2021-05-18 19:56 UTC, agunde406 commented on sdk/src/protocol/pike/payload.rs
>  pub enum Action {
Action could just be PikePayload since PikePayload only has the action as a field.

2021-05-18 20:35 UTC, dplumb94 approved these changes

2021-05-19 16:25 UTC, RyanLassigBanks commented on sdk/src/protocol/pike/payload.rs
>  pub enum Action {
I think this change makes sense, but that would make the builder kind of pointless, so I would suggest removing that as well. Also this would make the structure of the pike payload substantially different from the payload structs for the other protocols. If people are ok with then, I'm cool with making this change. Thoughts @vaporos @dplumb94 @dnewh ?

2021-05-20 17:39 UTC, dplumb94 commented on sdk/src/protocol/pike/payload.rs
>  pub enum Action {
Hmm it looks like the other payload structs have a timestamp field. I think it would actually make more sense to add that timestamp field to this transaction to match the others.

2021-05-20 17:43 UTC, agunde406 commented on sdk/src/protocol/pike/payload.rs
>  pub enum Action {
If that gets added, then I'm fine with it staying like this.

2021-05-24 18:59 UTC, agunde406 commented on ui/protos/pike_payload.proto
> +  uint64 timestamp = 6;
This proto file does not match the other proto file changed above, should this just be updated in the future when the whole protobuf is updated?

2021-05-24 19:02 UTC, peterschwarz commented on sdk/src/protocol/pike/payload.rs
> +    timestamp: u64,
Should the field on protocol object be a `Duration`?  The u64/seconds would be at the protobuf level, and it would give some strongly-typed meaning here.

Granted, it should also match the other instances of timestamps. If they are all currently u64's, then perhaps a story could be opened to cover changing all of them to the appropriate field type.

2021-05-25 13:44 UTC, RyanLassigBanks commented on ui/protos/pike_payload.proto
> +  uint64 timestamp = 6;
Reverted changes to this file

2021-05-25 14:03 UTC, RyanLassigBanks commented on sdk/src/protocol/pike/payload.rs
> +        let timestamp = self.timestamp.ok_or_else(|| {
This is meant to be consistent with the implementations [ProductPayloadBuilder](https://github.com/hyperledger/grid/blob/f0842a908da7f10ecc2540a4afc18e1090954f72/sdk/src/protocol/product/payload.rs#L178) and [LocationPayloadBuilder](https://github.com/hyperledger/grid/blob/f0842a908da7f10ecc2540a4afc18e1090954f72/sdk/src/protocol/location/payload.rs#L213)

2021-05-25 14:03 UTC, RyanLassigBanks commented on sdk/src/protocol/pike/payload.rs
> +    timestamp: u64,
All the other instances of timestamps in the protocol module are `u64`.

2021-05-25 14:10 UTC, agunde406 approved these changes

2021-05-25 14:10 UTC, peterschwarz commented on sdk/src/protocol/pike/payload.rs
> +    timestamp: u64,
Opened #710 to cover this detail.

2021-05-26 15:50 UTC, dplumb94 approved these changes

2021-05-26 21:42 UTC, merged