Update signer to match splinter's pattern
hyperledger/grid pull request #698
Opened 2021-05-19 19:05 UTC by KevinAnsleyJohnson

2021-05-26 18:18 UTC, peterschwarz commented on cli/src/actions/locations.rs
> -use std::{
Some of these use statements have been re-ordered unnecessarily.

2021-05-26 18:18 UTC, peterschwarz commented on cli/src/actions/agents.rs
> +    signer: Box<dyn Signer>,
Do functions need to own the signer?  If not, this could be typed `&dyn Signer`.

2021-05-26 19:21 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> -use std::{
That's the rust linter's preference :)

2021-05-26 19:49 UTC, KevinAnsleyJohnson commented on cli/src/actions/agents.rs
> +    signer: Box<dyn Signer>,
I'm not sure whether the functions need to own the signer or not - it was done this way to align with Splinter's cli.

2021-05-27 22:38 UTC, vaporos requested changes

2021-05-27 22:38 UTC, vaporos commented on cli/src/signing.rs
> +#[allow(dead_code)]
Please exclude jwt support entirely for now or guard jwt support with an experimental feature "cylinder-jwt".

2021-05-27 22:38 UTC, vaporos commented on cli/Cargo.toml
> +cylinder = { version = "0.2.2", features = ["jwt", "key-load"] }
See jwt comment below. If kept, pull in jwt support via a dependency on an experimental feature.

2021-05-27 22:38 UTC, vaporos commented on cli/src/actions/agents.rs
> +use std::collections::HashMap;
Since this re-orders the use statements, it would be good to conform to grouping them in the order of: std, external crates, crate, module with empty between the groupings (to prevent rust fmt from reordering). Unfortunately we don't have a lint for this.

2021-05-27 22:38 UTC, vaporos commented on cli/src/actions/locations.rs
> -use std::{
Best practice (for this project anyway) is to let the reviewer resolve their own comments as a double-check.

The re-ordering occurred because of the removal of the newline. See the previous comment on the right grouping of use statements.

2021-05-27 22:38 UTC, vaporos commented on cli/src/transaction.rs
> +        // let private_key = self.signer.()?; //key::load_signing_key(self.key_name.clone())?;
Commented out code isn't allowed in the project.

2021-05-27 22:51 UTC, vaporos commented on cli/src/actions/agents.rs
> +    signer: Box<dyn Signer>,
I don't recall why I didn't do &dyn Signer in Splinter, but IIRC I did attempt that and ended up with Box<dyn Signer> because I couldn't easily resolve some compiler issue without modifying cylinder.

2021-05-28 13:43 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> -use std::{
Ah! thanks for letting me know (about both things). Will fix!

2021-05-28 13:44 UTC, KevinAnsleyJohnson commented on cli/Cargo.toml
> +cylinder = { version = "0.2.2", features = ["jwt", "key-load"] }
I think it is better to remove in this case, because there truly is no implementation.

2021-05-28 13:45 UTC, KevinAnsleyJohnson commented on cli/src/actions/agents.rs
> +use std::collections::HashMap;
Ok! Sounds good. will fix!

2021-05-28 14:56 UTC, KevinAnsleyJohnson commented on cli/src/transaction.rs
> +        // let private_key = self.signer.()?; //key::load_signing_key(self.key_name.clone())?;
completed.

2021-05-28 14:57 UTC, KevinAnsleyJohnson commented on cli/Cargo.toml
> +cylinder = { version = "0.2.2", features = ["jwt", "key-load"] }
completed.

2021-06-02 14:21 UTC, vaporos approved these changes

2021-06-02 14:22 UTC, peterschwarz approved these changes

2021-06-02 14:23 UTC, merged