Have only one DEFAULT_GRID_PROTCOL_VERSOIN const
hyperledger/grid pull request #700
Opened 2021-05-20 18:47 UTC by RyanLassigBanks

Signed-off-by: Ryan Banks <rbanks@bitwise.io>

2021-05-24 20:40 UTC, agunde406 commented on sdk/src/rest_api/actix_web_3/routes/agents.rs
> +use super::DEFAULT_GRID_PROTOCOL_VERSION;
Typo in commit message:  DEFAULT_GRID_PROTCOL_VERSOIN -> DEFAULT_GRID_PROTOCOL_VERSION

2021-05-25 14:18 UTC, peterschwarz requested changes
Typo in commit message `_VERSOIN` -> `_VERSION`

2021-05-26 18:48 UTC, dplumb94 approved these changes

2021-05-26 20:57 UTC, peterschwarz approved these changes

2021-05-27 13:21 UTC, merged