Move sdk permissions into pike/permissions module
hyperledger/grid pull request #705
Opened 2021-05-21 02:30 UTC by KevinAnsleyJohnson

/sdk/src/permissions.rs was split apart into two separate files,
"/sdk/pike/permissions/mod.rs" which contains the PermissionChecker
implementation, and "/sdk/pike/permissions/error.rs" which contains the
PermissionCheckerError implementation. This means also that the import
path changed from grid_sdk::permissions to grid_sdk::pike::permissions,
so the handler files requesting permissions has also updated.

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-05-28 19:17 UTC, dnewh approved these changes

2021-06-04 20:40 UTC, vaporos requested changes

2021-06-04 21:25 UTC, vaporos submitted a review, later dismissed

2021-06-04 21:25 UTC, vaporos commented
This needs to be rebased because of conflicts.

2021-06-04 21:35 UTC, KevinAnsleyJohnson reviewed
> This needs to be rebased because of conflicts.

Yep - just noticed that. It's now rebased!

2021-06-04 21:35 UTC, KevinAnsleyJohnson commented on sdk/src/pike/permissions/mod.rs
> +// Copyright 2021 Cargill Incorporated
fixed! thanks!

2021-06-10 12:19 UTC, KevinAnsleyJohnson commented
Can I get eyes on this? Checks are passing, and changes requested have been satisfied.

2021-06-14 17:31 UTC, dnewh submitted a review, later dismissed

2021-06-14 17:51 UTC, dplumb94 requested changes

2021-06-14 17:51 UTC, dplumb94 commented on sdk/src/pike/permissions/mod.rs
> +    cfg_if! {
I think we only need `use sawtooth_sdk::processor::handler::ContextError;` since the tests shouldnt be getting compiled to wasm

2021-06-15 16:42 UTC, dplumb94 approved these changes

2021-06-15 16:45 UTC, dnewh approved these changes

2021-06-15 16:58 UTC, merged