Update help with env var defaults
hyperledger/grid pull request #729
Opened 2021-06-03 13:23 UTC by KevinAnsleyJohnson

`Key` option help information updated to include GRID_DAEMON_PATH and
CYLINDER_PATH defaults. `service_id` option help was updated to include
GRID_SERVICE_ID environment variable. `url` option help was updated to
include GRID_SERVICE_ENDPOINT default.

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-03 13:27 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> -                            .arg(
Noticed that this implementation was duplicating already existing code above. so it was redundant that therefore removed.

2021-06-03 13:27 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> +                    .arg(
Man page specified that there would be both a `draft` - which is by default, and a `not-draft`. Updated this implementation to match the man-page, because draft is a flag and is set to true by default, there would be no way of setting it to false. Also draft and not-draft is the convention used for other components. This method is not yet implemented so it should have no impact on the application.

2021-06-03 15:45 UTC, vaporos commented on cli/src/main.rs
> -                            .arg(
Can you break this out to a separate commit?

2021-06-03 15:46 UTC, vaporos commented on cli/src/main.rs
> +                    .arg(
Can you break this out into a separate commit?

2021-06-03 16:00 UTC, vaporos requested changes
In the past, we have resisted extremely long usage lines (as this is very common in Linux command usage statements, trying to target more "git commit -h" than "git commit --help".

The trade-off is essentially between concise quick-reference and verbose completeness, and we've previously favored concise with the assumption the man page covers completeness. 

ew have at times however, used a "DETAILS:" section to expand upon how the command works if its truly necessary.

For example, the most complex command across projects is "splinter circuit propose" which looks something like:

```
splinter-circuit-propose
Propose that a new circuit is created

USAGE:
    splinter circuit propose [FLAGS] [OPTIONS] --node <node>... --node-file <node_file> --service <service>... --template <template>

FLAGS:
    -n, --dry-run    Print circuit definition without submitting the proposal
    -h, --help       Prints help information
    -q, --quiet      Do not display output
    -V, --version    Prints version information
    -v               Log verbosely

OPTIONS:
        --comments <comments>                           Add human-readable comments to the proposal
        --compat <compat_version>
            Enforce that the proposed circuit is compatible with a specific version [possible values: 0.4, 0.6]

        --display-name <display_name>                   Add human-readable name for the circuit
    -k, --key <private-key-file>                        Path to private key file
        --management <management_type>                  Management type for the circuit
        --metadata <application_metadata>...            Application metadata of the proposal
        --metadata-encoding <metadata_encoding>
            Set encoding of application metadata (default: string) [possible values: json, string]

        --node <node>...
            Node that is part of a circuit (<node_id>::<endpoint1>,<endpoint2>)

        --node-file <node_file>                         File system path or HTTP(S) URL to nodes file
        --service <service>...                          Service ID and allowed nodes (<service-id>::<allowed_nodes>)
        --service-arg <service_argument>...             Pass arguments to a service (<service_id>::<key>=<value>)
        --service-peer-group <service_peer_group>...    List of peer services (comma-separated list)
        --service-type <service_type>...                Service type (<service_id>::<service_type>)
        --template <template>                           Template name to be applied to circuit
        --template-arg <template_arg>...                Arguments for the template argument (<key>=<value>)
    -U, --url <url>                                     URL of Splinter Daemon

DETAILS:
    One or more nodes must be specified using the --node and/or --node-file arguments. These
    arguments can be used on their own or together, but at least one of them is required.

    The --node-file argument must be a valid YAML file. A valid YAML file will be a list of nodes,
    where each node has an 'identity' or 'node_id' field, as well as an 'endpoints' field. Example:
        ---
        - identity: 'node-1'
          endpoints:
            - tcps://node-1-endpoint:8044
        - node_id: 'node-2'
          endpoints:
            - tcps://node-2-endpoint:8045

    For the --service-arg, --service-peer-group, and --service-type options, service IDs can be
    wildcarded with '*' to match multiple services. For example, '--service-type *::scabbard' match
    all services, and '--service-type sc*::scabbard' will match all services with IDs that start
    with 'sc'.

    With '--metadata-encoding string' (the default), the --metadata option takes a single string
    value and the --metadata option can be used only once. With '--metadata-encoding json', the
    --metadata option takes a key/value pair in the format '<key>=<value>', where '<value>' is a
    simple string, a JSON array, or a JSON object; the --metadata option can be used multiple times
    with JSON encoding.
```

2021-06-03 16:00 UTC, vaporos commented on cli/src/main.rs
> +                                    GRID_DAEMON_PATH variable, and if not present may be set with CYLINDER_PATH \
Was this intended to be GRID_DAEMON_KEY instead of GRID_DAEMON_PATH?

2021-06-04 11:12 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> -                            .arg(
Absolutely - I was wondering that myself.

2021-06-04 11:12 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> +                    .arg(
yes - Will remove from this PR

2021-06-04 12:22 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> +                    .arg(
This is now removed.

2021-06-04 12:22 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> -                            .arg(
Ok - This is now removed, and will be in a separate PR

2021-06-04 12:22 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> +                                    GRID_DAEMON_PATH variable, and if not present may be set with CYLINDER_PATH \
Yes - now fixed! Thanks!

2021-06-04 12:41 UTC, closed without merging