Update man pages for agent commands
hyperledger/grid pull request #736
Opened 2021-06-04 14:44 UTC by KevinAnsleyJohnson

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-04 20:36 UTC, dnewh commented on cli/man/grid-agent-create.1.md
> +: Roles assigned to the agent. May specify more than once.
This also accepts a comma-separated list. Perhaps this should be included in this description too

2021-06-04 21:11 UTC, KevinAnsleyJohnson commented on cli/man/grid-agent-create.1.md
> +: Roles assigned to the agent. May specify more than once.
that's true - qq: should it be named "roles" instead of "role"?

2021-06-04 21:48 UTC, vaporos requested changes

2021-06-04 21:48 UTC, vaporos commented on cli/man/grid-agent.1.md
> +: Path used to sign transactions if `k` or `--key`
Perhaps: "Colon-separated path used to search for the key which will be used to sign transactions."

I'm not sure how GRID_DAEMON_KEY is implemented, but if it is a straight-up replacement for "-k/--key", then there are multiple ways that it might interact with CYLINDER_PATH. If a "/" is present, it is interpreted as either a relative path or absolute path to the key file itself. If it does not include a "/" then it is the "base name" of the key, and all the directories listed in CYLINDER_PATH will be searched (in order) for a file called KEY.priv.

2021-06-04 21:48 UTC, vaporos commented on cli/man/grid-agent-create.1.md
> +: Base name for private signing key file. (either a file path or the name of a
"Base name" here is not technically correct, since if it has a "/" then it is interpreted as the full path to the file. In other words, the key option should:

--key=mykey # search all directories in CYLINDER_PATH for mykey.priv
--key=./mykey.priv # use the file ./mykey.priv
--key=path/mykey.priv # use the file ./path/mykey.priv
etc.

The second sentence should start with an E and the period should be within the parens, or the period preceding the parens should be omitted (depending on intent).

2021-06-04 21:48 UTC, vaporos commented on cli/man/grid-agent-create.1.md
> +: Roles assigned to the agent. May specify more than once.
If it can be specified using a delimiter, then it could be changed to the plural form. We've kept aliases for the non-plural form in other places, but hidden them and not documented them.

2021-06-09 14:35 UTC, KevinAnsleyJohnson commented on cli/man/grid-agent.1.md
> +: Path used to sign transactions if `k` or `--key`
Updated!

2021-06-09 14:35 UTC, KevinAnsleyJohnson commented on cli/man/grid-agent-create.1.md
> +: Base name for private signing key file. (either a file path or the name of a
Updated!

2021-06-10 12:17 UTC, KevinAnsleyJohnson commented on cli/man/grid-agent-create.1.md
> +: Roles assigned to the agent. May specify more than once.
description is now updated to include comma-separated list. pluralization of a cli command should be a separate commit, if we want to do it.

2021-06-14 18:46 UTC, dnewh approved these changes

2021-06-14 20:07 UTC, vaporos approved these changes

2021-06-14 20:07 UTC, merged