Update man pages for PO and PO Version Commands
hyperledger/grid pull request #738
Opened 2021-06-04 16:06 UTC by KevinAnsleyJohnson

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-07 14:44 UTC, vaporos requested changes
See comments on #736, which would apply here as well.

2021-06-15 17:40 UTC, dplumb94 requested changes

2021-06-15 17:40 UTC, dplumb94 commented on cli/man/grid-po-create.1.md
> +: Specify the organization that owns the purchase order. required.
I think this should say "Specify the organization that owns the purchase order. This option is required." as the example for grid po version createe.

2021-06-16 21:24 UTC, dplumb94 submitted a review, later dismissed

2021-06-23 15:44 UTC, dplumb94 approved these changes

2021-06-23 17:27 UTC, vaporos approved these changes

2021-06-23 17:27 UTC, merged