Update man pages for Organization commands
hyperledger/grid pull request #739
Opened 2021-06-04 16:16 UTC by KevinAnsleyJohnson

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-04 20:07 UTC, dnewh approved these changes

2021-06-07 14:45 UTC, vaporos requested changes
See comments on #736, which would apply here as well.

2021-06-15 17:46 UTC, dplumb94 commented on cli/man/grid-organization-update.1.md
> +  Splinter. Format <circuit-id>::<service-id>.
Would be nice to standardize the format descriptions. We have `(format: <id_type>:<id>)` and `Format <circuit-id>::<service-id>`

2021-06-15 18:15 UTC, KevinAnsleyJohnson commented on cli/man/grid-organization-update.1.md
> +  Splinter. Format <circuit-id>::<service-id>.
done!

2021-06-23 16:39 UTC, dplumb94 requested changes

2021-06-23 16:39 UTC, dplumb94 commented on cli/man/grid-organization-create.1.md
> +: base name or path to a private signing key file.
The b should be capitalized here

2021-06-23 21:44 UTC, dplumb94 approved these changes

2021-06-29 15:54 UTC, dplumb94 approved these changes

2021-07-01 13:36 UTC, vaporos approved these changes

2021-07-01 13:36 UTC, merged