Update man pages for product commands
hyperledger/grid pull request #740
Opened 2021-06-04 16:31 UTC by KevinAnsleyJohnson

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-04 18:06 UTC, dnewh submitted a review, later dismissed

2021-06-07 14:45 UTC, vaporos reviewed
See comments on #736, which would apply here as well.

2021-06-07 14:50 UTC, vaporos requested changes
Meant to request changes - See comments on #736, which would apply here as well.

2021-06-15 16:31 UTC, KevinAnsleyJohnson commented on cli/man/grid-product-list.1.md
> +List all products in grid. If the `service_id` option is specified, only
According to the implementation, we _still_ use GRID_SERVICE_ID env var to set the default. Is this what we want? or should the implementation change for `grid product list` to not use the GRID_SERVICE_ID env var?

This man-page is accurate to the implementation. Happy to take this on if needed, outside the current story.

2021-06-15 16:31 UTC, KevinAnsleyJohnson commented on cli/man/grid-product-list.1.md
> +: Specifies a default value for `--service-id`
Yes - it's used as a default here. maybe that is acceptable?

2021-06-17 16:23 UTC, dplumb94 requested changes

2021-06-23 21:45 UTC, dplumb94 submitted a review, later dismissed

2021-06-28 16:31 UTC, shannynalayna submitted a review, later dismissed

2021-06-29 15:54 UTC, dplumb94 approved these changes

2021-06-29 15:55 UTC, dplumb94 requested changes
"Create new products from a YAML file." is not accurate anymore since we can either use a GDSN XML file, YAML file, or specify properties directly on the CLI.

This comment wasn't addressed

2021-06-30 17:17 UTC, KevinAnsleyJohnson commented
> "Create new products from a YAML file." is not accurate anymore since we can either use a GDSN XML file, YAML file, or specify properties directly on the CLI.
> 
> This comment wasn't addressed

Yep - I see that. I just updated the PR.

2021-06-30 18:36 UTC, dplumb94 approved these changes

2021-07-01 13:39 UTC, vaporos approved these changes

2021-07-01 13:39 UTC, merged