Ignore test_db file
hyperledger/grid pull request #741
Opened 2021-06-04 18:25 UTC by dnewh

Running `cargo test` with experimental daemon features enabled generates
a sqlite `test_db` file. This file should never be checked in. This adds
that file to the .gitignore and .dockerignore files.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-06-04 18:32 UTC, peterschwarz reviewed
Make sure it is added to any dockerignore files

2021-06-04 19:01 UTC, KevinAnsleyJohnson submitted a review, later dismissed
LGTM

2021-06-04 21:23 UTC, vaporos requested changes
The test should be modified to create this in a temporary directory and then clean it up after.

2021-06-14 17:38 UTC, vaporos approved these changes

2021-06-14 18:04 UTC, dplumb94 requested changes

2021-06-14 18:04 UTC, dplumb94 commented on daemon/src/rest_api/mod.rs
> +        // let pool = create_connection_pool_and_migrate();
remove commented code

2021-06-14 18:10 UTC, dnewh commented on daemon/src/rest_api/mod.rs
> +        // let pool = create_connection_pool_and_migrate();
fixed

2021-06-14 18:11 UTC, dplumb94 approved these changes
Worked locally, LGTM

2021-06-14 18:53 UTC, vaporos approved these changes

2021-06-14 20:19 UTC, merged