Update man pages for role commands
hyperledger/grid pull request #742
Opened 2021-06-04 19:00 UTC by KevinAnsleyJohnson

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-04 19:03 UTC, KevinAnsleyJohnson commented on cli/man/grid-role-update.1.md
> +`-p`,`--permissions`
of all the roles, only update had a short `-p`. considering altering the main.rs to either remove -p for consistency, or to add -p to the other usecases. suggestions?

2021-06-04 20:04 UTC, dnewh commented on cli/man/grid-role-update.1.md
> +`-p`,`--permissions`
My opinion is that `-p` should be an option for all the usecases

2021-06-04 20:06 UTC, KevinAnsleyJohnson commented on cli/man/grid-role-update.1.md
> +`-p`,`--permissions`
I'll make a separate PR for that then, because it goes beyond the scope of the task.

2021-06-07 14:51 UTC, vaporos requested changes
See comments on #736, which would apply here as well.

2021-06-23 17:29 UTC, vaporos approved these changes

2021-06-23 17:33 UTC, dplumb94 requested changes

2021-06-23 17:33 UTC, dplumb94 commented on cli/man/grid-role-update.1.md
> +: base name or path to a private signing key file.
b should be capitalized

2021-06-23 21:45 UTC, dplumb94 approved these changes

2021-06-28 16:05 UTC, shannynalayna commented on cli/man/grid-role-create.1.md
> +: Set role as inactive. conflicts with `--active`.
Perhaps this period should be a comma, or capitalize the 'conflicts'. This happens with both instances of conflicts

2021-06-28 16:08 UTC, dnewh approved these changes

2021-06-28 16:08 UTC, dplumb94 approved these changes

2021-06-28 16:08 UTC, shannynalayna approved these changes

2021-06-29 15:54 UTC, merged