Update man pages for schema commands
hyperledger/grid pull request #744
Opened 2021-06-04 20:24 UTC by KevinAnsleyJohnson

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-07 14:52 UTC, vaporos requested changes
See comments on #736, which would apply here as well.

2021-06-23 17:31 UTC, vaporos approved these changes

2021-06-23 17:34 UTC, dplumb94 requested changes

2021-06-23 17:34 UTC, dplumb94 commented on cli/man/grid-schema-create.1.md
> +: base name or path to a private signing key file.
b should be capitalized

2021-06-23 21:47 UTC, dplumb94 approved these changes

2021-06-28 16:06 UTC, shannynalayna commented on cli/man/grid-schema-create.1.md
> +schemas can be created by using the `create` command.
'schemas' should be capitalized here

2021-06-28 16:09 UTC, shannynalayna commented on cli/man/grid-schema-update.1.md
> +schemas can be updated by using the `update` command.
'schemas' should be capitalized here as well

2021-06-28 16:14 UTC, shannynalayna approved these changes

2021-06-30 19:00 UTC, dplumb94 approved these changes

2021-06-30 19:01 UTC, merged