Check all required schema for product / location
hyperledger/grid pull request #754
Opened 2021-06-09 20:35 UTC by KevinAnsleyJohnson

Instead of short-circuiting at any CliError in yaml_to_property_values
functions, iterate through the entire payload and return a more
comprehensive list of errors. Because we're coalescing the CliError
types, I chose InvalidYamlError to encapsulate the differing types
of CliErrors that may occur, most commonly PayloadError and UserError.

2021-06-09 20:40 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> +                CliError::UserError(str) => Some(str.to_string()),
Wondering - should I exhaust the match cases? I believe UserError and PayloadError capture all possible errors, but including IoError and InvalidYamlError because we do file opening and yaml parsing on line 285.

2021-06-09 20:40 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> +        Err(CliError::InvalidYamlError(format!(
I chose InvalidYamlError as an overarching error. I could alternatively send multiple errors back, but then would need more handling.

2021-06-10 11:53 UTC, KevinAnsleyJohnson commented on cli/src/actions/products.rs
> +        return Err(CliError::UserError(format!("Field {} not found", def.name)));
The original function listed this as a UserError, but would this ultimately be a Payload Error?

2021-06-16 15:45 UTC, dplumb94 commented on cli/src/actions/locations.rs
> +        Err(CliError::InvalidYamlError(format!(
Hmm yeah this is tricky. Ultimately I think the top level error should be UserError. The thing the user really needs to know is the errors that come from checking the submitted product definition against the schema. Things like IO errors or payload errors (coming from serializing the protobuf) are internal and not really actionable by the user, so it might not make sense to include them in this list. It might make more sense to just short circuit and return one of those errors at that point.

2021-06-24 14:42 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> +                    CliError::EmptyError => {
Notice the new type: EmptyError - This is in response to our discussion of how many times we have errors that are never propagated to the CLI. Not sold on this approach, but offering it more as a RFC.

2021-06-24 14:42 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> +            Err(CliError::EmptyError) => {
Because of the recursive nature of the function and its helper, we don't want to report the same error at multiple nested levels. We just want to note that an error occurred, and have confidence that the causes of EmptyError (Payload or User Errors) have been reported via the `error!` macro. an emptyError occurring at any level of nesting will eventually be handled with proper verbiage higher up on the call stack, as found on lines 204 and 233.

2021-06-25 13:12 UTC, vaporos requested changes

2021-06-25 13:12 UTC, vaporos commented on cli/src/actions/locations.rs
> +                    CliError::EmptyError => {
We should consider removing CliError entirely in favor of InternalError taken from libsplinter.

Here is some high-level info: https://www.splinter.dev/community/error_handling_best_practices.html

We could start this by adding InternalError to the CliError enum:

```
enum CliError {
...
    InternalError(InternalError),
...
}
```

And over time, reducing that enum as we collapse things into InternalError, and potentially removing CliError completely at some point.

Other errors could be used more locally, where we need a function to return an enum so we can differentiate between multiple errors; but the end result would always be to eventually convert to an InternalError and start propagating that up the stack.

It is important to note the meaning of "InternalError" -- "this error has no meaning to the calling function, other than that an error occurred". It does not mean "not caused by the user".

2021-06-25 13:23 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> +                    CliError::EmptyError => {
Brilliant!! I totally agree with this approach. Thanks Shawn!

2021-07-01 13:44 UTC, vaporos commented on cli/src/error.rs
> +    InternalError(String),
This variant should be InternalError(InternalError) where the InternalError struct is the one from the Grid SDK.

2021-07-02 12:33 UTC, KevinAnsleyJohnson commented on cli/src/error.rs
> +    InternalError(String),
Thank Shawn! It's now updated.

2021-07-06 15:17 UTC, KevinAnsleyJohnson commented on cli/src/actions/products.rs
> +            "Nested Error".to_string(),
because this function is recursive, an InternalError firing N deep into the yaml tree would report N times, hence we want to ignore this with an internal error. At the top level we capture the internal error and respond that there was an error with the specific file.

2021-09-13 21:53 UTC, KevinAnsleyJohnson commented
## Testing this branch:

bash into gridd-alpha with proper GRID_SERVICE_ID and GRID_DAEMON_KEY set.
Run the setup scripts:
```
echo '  - name: gs1_location
    description: GS1 location schema
    owner: myorg
    properties:
      - name: locationDescription
        data_type: String
        description: ""
        required: true
      - name: locationType
        data_type: Enum
        description: ""
        enum_options: [
          ShipTo, BillTo, ShipFrom, PaidBy, OrderFrom, Recall, OrgEntity, RemitTo
        ]
        required: true
      - name: addressLine1
        data_type: String
        description: ""
        required: true
      - name: addressLine2
        data_type: String
        description: ""
        required: false
      - name: city
        data_type: String
        description: ""
        required: true
      - name: stateOrRegion
        data_type: String
        description: ""
        required: true
      - name: postalCode
        data_type: String
        description: ""
        required: true
      - name: country
        data_type: String
        description: ""
        required: true
      - name: latLongValue
        data_type: lat_long
        description: ""
        required: true
      - name: contactName
        data_type: String
        description: ""
        required: true
      - name: contactEmail
        data_type: String
        description: ""
        required: true
      - name: contactPhone
        data_type: String
        description: ""
        required: true
      - name: createDate
        data_type: Number
        number_exponent: 0
        description: ""
        required: true
      - name: inactivationDate
        data_type: Number
        number_exponent: 0
        description: ""
        required: false
      - name: parentLocation
        data_type: String
        description: ""
        required: false
      - name: industrySector
        data_type: Enum
        description: ""
        enum_options: [General, CPG, Healthcare, Foodservice]
        required: false
      - name: role
        data_type: Enum
        description: ""
        enum_options: [
          Manufacturer, SolutionsProvider, Undefined, Distributor,
          Provider, Supplier, 3rdParty, Warhouse, IndependentOperator, Operator]
        required: false
      - name: informationProviderGLN
        data_type: Number
        number_exponent: 0
        description: ""
        required: false' >> location_schema.yaml;

echo ' - namespace: "GS1"
   location_id: "0013600000011"
   owner: "myorg"
   properties:
     locationDescription: "test location"
     locationType: 0
     addressLine1: "251 Test St."
     city: "Minneapolis"
     stateOrRegion: "MN"
     postalCode: "55401"
     country: "United States"
     latLongValue: "449778,-932650"
     contactName: "John Tester"
     contactEmail: "tester@email.com"
     contactPhone: "6555555555"
     createDate: 1602706399'>> good_location.yaml;

echo ' - namespace: "GS1"
   location_id: "0013600000011"
   owner: "myorg"
   properties:
     wronglocationDescription: "test location"
     locationType: 0
     wrongaddressLine1: "251 Test St."
     wrongcity: "Minneapolis"
     wrongstateOrRegion: "MN"
     postalCode: "55401"
     country: "United States"
     latLongValue: "wrong449778,wrong-932650"
     contactName: "John Tester"
     contactEmail: "tester@email.com"
     contactPhone: "6555555555"
     createDate: 1602706399'>> bad_location.yaml;
```

then run the execution:
```
    grid schema create location_schema.yaml;
    grid location create -f good_location.yaml;
    grid location create -f bad_location.yaml;
```

good_location.yaml should post correctly, but
bad_location.yaml should fail, and show multiple errors

2021-09-27 15:18 UTC, vaporos commented on cli/src/actions/locations.rs
> +                        CliError::UserError(format!("Errors occurred while processing: {}", path))
To avoid throwing away the internal error message, this could be - ("Errors occurred while processing '{}': {}", path, e)

2021-09-27 15:21 UTC, vaporos commented on cli/src/actions/products.rs
> +                are_errors_present = true;
This should probably be logged with error!() as well.

2021-09-27 15:27 UTC, KevinAnsleyJohnson commented on cli/src/actions/products.rs
> +                are_errors_present = true;
I think an example would be helpful.

example:

- namespace: "GS1"
   location_id: "0013600000011"
   owner: "myorg"
   properties:
     locationDescription: "test location"
     locationType: 0
     addressLine1: "251 Test St."
     city: "Minneapolis"
     stateOrRegion: "" // error: stateOrRegion required
     postalCode: "55401"
     country: "United States"
     latLongValue: "449778," // error: cannot parse latLong
     contactName: "John Tester"
     contactEmail: "tester@email.com"
     contactPhone: "6555555555"
     createDate: 1602706399
  
this payload would show errors related to:
 - stateOrRegion required
 - cannot parse latLong

but, because it's nested under properties, we just want to notify the parent that an error occurred.

otherwise, it would show 3 errors:
 - stateOrRegion required
 - cannot parse latLong
 - Nested error

hence, the nested error is a necessary propogation tool. Another way to look at this is to remove the error state entirely, and instead send a valid flag to it's parent.

2021-09-27 15:30 UTC, KevinAnsleyJohnson commented on cli/src/actions/locations.rs
> +                        CliError::UserError(format!("Errors occurred while processing: {}", path))
Internal Error is only used as a propagation tool within the current context. If that's causing confusion, we could try to pass whether the state is valid or not.

2022-07-20 15:08 UTC, shannynalayna commented
Based on changing priorities and that this PR is out-of-date, it will be closed. Feel free to re-open when the merge conflicts are fixed, after rebasing to main, and existing comments are addressed. This PR may also need to be backported to 0-3 if re-opened on main.

2022-07-20 15:08 UTC, closed without merging