Fix CLI signing path for --key
hyperledger/grid pull request #770
Opened 2021-06-18 14:59 UTC by KevinAnsleyJohnson

current_user_serach_path() would look in root/.cylinder/keys, whereas we
have documentation that leads us to root/.grid/keys. This change aligns
code to the documentation.

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-06-18 17:06 UTC, dnewh reviewed
Nitpick: typo in commit message serach -> search

2021-06-18 18:20 UTC, dnewh approved these changes
Tested

2021-06-21 17:11 UTC, dnewh approved these changes

2021-06-21 17:11 UTC, vaporos requested changes

2021-06-21 17:11 UTC, vaporos commented on cli/src/signing.rs
> +                    let mut splinter_path = match dirs::home_dir() {
Should this be grid_path?

2021-06-21 19:22 UTC, dnewh approved these changes

2021-06-23 17:32 UTC, vaporos approved these changes

2021-06-23 17:32 UTC, merged