Stabilize product-gdsn
hyperledger/grid pull request #780
Opened 2021-06-24 18:52 UTC by dplumb94

2021-06-25 20:23 UTC, vaporos requested changes

2021-06-25 20:23 UTC, vaporos commented on sdk/Cargo.toml
> +    "reqwest", "quick-xml", "libc"
These should all be placed on the same line as the feature, or one-per-line; and alphabetical.

2021-06-28 18:31 UTC, peterschwarz requested changes

2021-06-28 18:31 UTC, peterschwarz commented on sdk/Cargo.toml
> +quick-xml = { version = "0.22", features = [ "serialize" ], optional = true }
This should be split into two commits - one that changes the dependency relationships and one that stabilizes the feature

2021-06-28 19:58 UTC, vaporos approved these changes

2021-06-29 17:58 UTC, dnewh approved these changes

2021-06-29 20:32 UTC, peterschwarz approved these changes

2021-06-29 20:33 UTC, merged