Add grid organization `list` and `show` commands
hyperledger/grid pull request #795
Opened 2021-07-02 14:50 UTC by shannynalayna

This change adds commands to list organizations and to show a specific organization based on the `org_id`. This also adds the man page entries for each of these commands.

2021-07-02 19:20 UTC, dplumb94 requested changes
current output for --csv looks like this
```
ORG_ID,NAME,LOCATIONS,ALTERNATE_IDScrgl,Cargill,,gs1_company_prefix:0, asdf:asdfMacBook-Pro:grid dplumb$ 
```

I think to fix this it just needs a newline at the end of that output.

Also please add the list and show commands to the grid-organization.1.md man page in the See Also section

2021-07-07 13:38 UTC, shannynalayna commented
> current output for --csv looks like this
> 
> ```
> ORG_ID,NAME,LOCATIONS,ALTERNATE_IDScrgl,Cargill,,gs1_company_prefix:0, asdf:asdfMacBook-Pro:grid dplumb$ 
> ```
> 
> I think to fix this it just needs a newline at the end of that output.
> 
> Also please add the list and show commands to the grid-organization.1.md man page in the See Also section

@dplumb94 I fixed the list --csv option to look more like the way agents are listed in the csv format (with newlines after each row, and each individual value wrapped in quotes. I also added a commit to add links to the list/show man pages to the rest of the grid-organization-* man pages.

2021-07-07 19:15 UTC, dplumb94 approved these changes

2021-07-07 21:46 UTC, dnewh approved these changes

2021-07-09 20:41 UTC, merged