Rename pike to grid_pike
hyperledger/grid pull request #800
Opened 2021-07-07 21:14 UTC by rbuysse

The rest of the grid contracts are prefixed with grid_, this change updates
pike to match.

Signed-off-by: Ryan Beck-Buysse <rbuysse@bitwise.io>

2021-07-08 14:33 UTC, rbuysse commented
```
root@scabbard-cli-beta:/# scabbard contract list --url http://splinterd-alpha:8085 --service-id NVSPJ-Sy7Bp::gsAA
NAME                VERSIONS OWNERS                                                             
grid-pike           2        03c262c30d4da983cda6d62fb34e1c5c603787ef291998105ca16372b1505b4623 
grid_location       1        03c262c30d4da983cda6d62fb34e1c5c603787ef291998105ca16372b1505b4623 
grid_purchase_order 1        03c262c30d4da983cda6d62fb34e1c5c603787ef291998105ca16372b1505b4623 
grid_product        1        03c262c30d4da983cda6d62fb34e1c5c603787ef291998105ca16372b1505b4623 
grid_schema         1        03c262c30d4da983cda6d62fb34e1c5c603787ef291998105ca16372b1505b4623 
```

2021-07-12 16:16 UTC, agunde406 requested changes

2021-07-12 16:16 UTC, agunde406 commented on contracts/pike/src/handler.rs
> +const GRID_PIKE_FAMILY_NAME: &str = "pike";
This still says the family name is pike?

2021-07-12 18:06 UTC, agunde406 approved these changes

2021-07-12 18:48 UTC, dnewh approved these changes

2021-07-12 18:49 UTC, merged