Add experimental support for Cylinder JWTs
hyperledger/grid pull request #839
Opened 2021-07-21 20:53 UTC by dnewh

This adds support for using Cylinder JWTs as an Auth header in requests
to submit batches. This new functionality is guarded behind the
experimental `cylinder-jwt-support` feature. This creates the Signer in
the the `run_splinter` function which is then passed through to the
REST API when that is set up.

Signed-off-by: Davey Newhall <newhall@bitwise.io>

2021-07-21 21:15 UTC, peterschwarz requested changes

2021-07-21 21:15 UTC, peterschwarz commented on daemon/Cargo.toml
> +cylinder-jwt-support = ["grid-sdk/cylinder-jwt-support"]
Instead of adding the `"jwt"` feature to the cylinder dependency, you should add it to this features list of feature dependancies as `"cylinder/jwt"`

2021-07-21 21:15 UTC, peterschwarz commented on daemon/src/rest_api/mod.rs
> +            _signer: Box<dyn Signer>,
Should this make use of the signer for tests?

2021-07-21 21:15 UTC, peterschwarz commented on daemon/src/rest_api/mod.rs
> +    // won't work with experimental features
Why not?

2021-07-21 21:15 UTC, peterschwarz commented on sdk/Cargo.toml
> +cylinder-jwt-support = ["cylinder"]
Same issue as the daemon feature.

2021-07-21 21:15 UTC, peterschwarz commented on sdk/src/rest_api/resources/batches/v1/handler.rs
> +    #[cfg(feature = "cylinder-jwt-support")] signer: Box<dyn Signer>,
Couldn't the signer be owned by the backend client? The sawtooth backend doesn't require this, it should be encapsulated by the backend implementation.

2021-07-21 21:17 UTC, dnewh commented on daemon/src/rest_api/mod.rs
> +            _signer: Box<dyn Signer>,
The tests run using a sawtooth backend

2021-07-22 14:03 UTC, shannynalayna commented on daemon/src/rest_api/mod.rs
> +    // won't work with experimental features
Are these tests run with `just test` ? Running that command on this pr, all tests passed

2021-07-22 14:03 UTC, shannynalayna commented on daemon/src/rest_api/mod.rs
> +    // won't work with experimental features
Are these tests run with `just test` ? Running that command on this pr, all tests passed

2021-07-22 18:24 UTC, dnewh commented
@peterschwarz @shannynalayna Updated by adding the signer to the BackendClient. This resolves the comments on this

2021-07-22 19:00 UTC, peterschwarz commented on daemon/src/rest_api/mod.rs
> +        #[cfg(not(feature = "cylinder-jwt-support"))]
Are these still relavant?

2021-07-22 19:15 UTC, dnewh commented on daemon/src/rest_api/mod.rs
> +        #[cfg(not(feature = "cylinder-jwt-support"))]
removed

2021-07-22 19:16 UTC, peterschwarz approved these changes

2021-07-23 20:41 UTC, shannynalayna approved these changes

2021-07-23 20:42 UTC, merged