Add Cylinder JWT support to app auth handler
hyperledger/grid pull request #891
Opened 2021-08-03 14:09 UTC by shannynalayna

This PR makes various updates to support the authorization requirements in Splinter 0.5. This updates the Splinter dep, and various others in support of this update, to 0.5 within the Grid daemon. Authorization, in the form of Cylinder JWTs, has been added to all requests sent to the Splinter backend. This also updates the Signer used by the app auth handler to a Cylinder signer, allowing the JWT to be formed from this signer and added to rest requests. 

This functionality is behind the experimental `cylinder-jwt-support` feature.

2021-08-12 21:03 UTC, dnewh approved these changes
tested

2021-08-13 20:34 UTC, dplumb94 commented on examples/splinter/docker-compose.yaml
> +    image: splintercommunity/splinter-cli:0.5
Is this considered a dev image? I dont think we should depend on any dev images in Grid (unless we have a special docker-compose file for that).

2021-08-13 20:35 UTC, dplumb94 requested changes
I think we should keep the default docker example for Splinter using the stable release. We could create another one for testing 0.5.

2021-09-15 19:19 UTC, shannynalayna commented
Rather than updating the daemon to an experimental Splinter release, we're going to wait until we have a clear upgrade path for Grid 0.2. Therefore, more tests must be conducted using Grid 0.2 as-is with Splinter 0.5/0.6 before we work on updating Grid's dependencies.

2021-09-15 19:19 UTC, closed without merging