Refactor SDE transaction handling
hyperledger/grid pull request #897
Opened 2021-08-06 19:43 UTC by dnewh

This PR updates the SDE to properly run database operations in a transaction. To facilitate this, two new `StoreFactory` traits were introduced, `TransactionalStoreFactory` and `InContextStoreFactory`, that expose this functionality in the daemon. These traits allow for the creation of a `StoreFactory` that can be used to initialize a transaction, get various Grid stores, and then run DB operations all within a transaction on a single Connection. Previously, there was no guarantee that operations were run within the same transaction as each operation got a Connection from a ConnectionPool individually.

2021-08-09 17:53 UTC, shannynalayna commented on daemon/src/database/mod.rs
> +    pub fn _get(&self) -> Result<PooledConnection<ConnectionManager<C>>, DatabaseError> {
Could this function just be removed?

2021-08-09 17:53 UTC, shannynalayna commented on daemon/src/splinter/app_auth_handler/mod.rs
> +
Unnecessary change here

2021-08-09 18:07 UTC, dnewh commented on daemon/src/database/mod.rs
> +    pub fn _get(&self) -> Result<PooledConnection<ConnectionManager<C>>, DatabaseError> {
updated

2021-08-09 18:08 UTC, dnewh commented on daemon/src/splinter/app_auth_handler/mod.rs
> +
updated

2021-08-09 18:35 UTC, peterschwarz requested changes

2021-08-09 18:35 UTC, peterschwarz commented on sdk/src/batches/store/diesel/mod.rs
> +    C: diesel::Connection<TransactionManager = AnsiTransactionManager> + 'static,
Do the constraints need to be this explicit in these structs?

2021-08-09 18:35 UTC, peterschwarz commented on daemon/src/database/mod.rs
> + * Copyright 2019-2021 Cargill Incorporated
Typo in commit message: InContextStoreFactorys -> InContextStoreFactory

2021-08-09 18:35 UTC, peterschwarz commented on daemon/src/event/db_handler.rs
> +    pub fn from_store_factory(store_factory: Box<dyn TransactionalStoreFactory>) -> Self {
This could probably just be called `new`

2021-08-09 18:35 UTC, peterschwarz commented on daemon/src/event/db_handler.rs
> +                    .resolve_fork(commit.commit_num)?;
These errors are missed, and would cause the state of the transaction to be neither rolled back nor committed.  The whole block of code that makes use of the transaction should be surrounded in a closure that returns `Result<(), EventError>` and then that result can be evaluated and the transaction committed or rolled back.

2021-08-09 21:13 UTC, dnewh commented on sdk/src/batches/store/diesel/mod.rs
> +    C: diesel::Connection<TransactionManager = AnsiTransactionManager> + 'static,
After discussing, leaving this due to nested transactions.

2021-08-09 21:16 UTC, dnewh commented on daemon/src/database/mod.rs
> + * Copyright 2019-2021 Cargill Incorporated
updated

2021-08-09 21:16 UTC, dnewh commented on daemon/src/event/db_handler.rs
> +    pub fn from_store_factory(store_factory: Box<dyn TransactionalStoreFactory>) -> Self {
updated

2021-08-09 21:16 UTC, dnewh commented on daemon/src/event/db_handler.rs
> +                    .resolve_fork(commit.commit_num)?;
updated

2021-08-09 21:45 UTC, peterschwarz approved these changes

2021-08-10 13:47 UTC, peterschwarz approved these changes

2021-08-10 17:27 UTC, merged