Add workflow-aware "Create PO" action
hyperledger/grid pull request #912
Opened 2021-08-26 13:07 UTC by shannynalayna

This change adds an implementation to the purchase order smart contract's "create po" action. This action is implemented using the workflow-aware permission check.

2021-09-10 15:51 UTC, dnewh approved these changes

2021-09-15 16:36 UTC, dnewh submitted a review, later dismissed

2021-09-16 19:53 UTC, dnewh requested changes

2021-09-16 19:53 UTC, dnewh commented on contracts/purchase_order/src/handler.rs
> +                    ._check_permission_with_workflow(
This should probably also get rid of the "_" on the `check_permission_with_workflow` fn now that it's being used

2021-09-16 20:25 UTC, shannynalayna commented on contracts/purchase_order/src/handler.rs
> +                    ._check_permission_with_workflow(
Updated!

2021-09-16 21:27 UTC, dnewh approved these changes

2021-09-17 19:30 UTC, dnewh approved these changes

2021-09-20 16:19 UTC, leebradley approved these changes

2021-09-20 16:19 UTC, KevinAnsleyJohnson approved these changes

2021-09-20 17:22 UTC, agunde406 approved these changes

2021-09-20 17:31 UTC, merged