Add purchase order list and show functionality
hyperledger/grid pull request #915
Opened 2021-08-31 19:38 UTC by KevinAnsleyJohnson

Added purchase order list and show functionality in the CLI. This 
included updating the SDK client's fetch_entities_list to support 
multiple query string parameters via a hashmap, implementing list and 
show for purchase orders within ReqwestPurchaseOrderClient, and 
implementing the list and show functionality for the CLI.

2021-08-31 19:54 UTC, KevinAnsleyJohnson commented on cli/src/actions/purchase_orders.rs
> +                .unwrap_or_else(|_| "Cannot Format Purchase Order".to_string());
This maybe should match and choose to print an err!() vs a println!(). Thoughts?

2021-08-31 19:54 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> +                        is_closed: if m.is_present("closed") {
I chose against a builder here because every field is optional. Not sure if there's a cleaner way to do it.

2021-09-01 16:40 UTC, shannynalayna commented on sdk/src/client/reqwest.rs
> -
This change looks unrelated to this commit

2021-09-01 16:42 UTC, shannynalayna commented on sdk/src/client/purchase_order/reqwest.rs
> +            // Note: This filter is not currently implemented in rest api
I think for now we should remove these notes and you should add a story to implement the filters in the po rest api - as it will be difficult to keep track of these comments to be removed when it is implemented

2021-09-01 16:47 UTC, shannynalayna commented on sdk/src/client/purchase_order/reqwest.rs
> +fn boolean_to_str(value: &bool) -> &'static str {
I think you are able to use `to_string()` on a bool value in rust, so you could just call `&is_closed.to_string()` rather than implementing this separate function

2021-09-01 17:41 UTC, shannynalayna requested changes

2021-09-01 17:41 UTC, shannynalayna commented on cli/src/actions/purchase_orders.rs
> +use std::time::SystemTime;
Missing a copyright on this file

2021-09-01 17:41 UTC, shannynalayna commented on cli/src/actions/purchase_orders.rs
> +                        // Note: Summary fields for order_xml_3_4 have not been decided yet.
Again, I think this should become a story and removed as a note from the code

2021-09-01 17:41 UTC, shannynalayna commented on cli/src/actions/purchase_orders.rs
> +            None => {
If there is no accepted version, we should just not write out anything, I think

2021-09-01 17:41 UTC, shannynalayna commented on cli/src/actions/purchase_orders.rs
> +                        write!(f, "\nRevision N/A")?;
Same here, if the revision doesn't exist, I don't think we should print anything out

2021-09-01 17:41 UTC, shannynalayna commented on cli/src/actions/purchase_orders.rs
> +        write!(f, "\n\t{:18}{}", "organization", &self.org_id)?;
Hm, so after looking at how this writes out, I think it would make more sense if it were formatted like this: 
```
Purchase Order <UUID>:
        Organization: <Org ID>
        Workflow Status: <workflow status>
        Created At: <created at timestamp>
        Closed: <is_closed bool>
```
And then we can check if there is the accepted version and print it in a similar format

2021-09-01 17:41 UTC, shannynalayna commented on cli/src/actions/purchase_orders.rs
> +        // Note: purchase order number is not in payload today.
We should also change (across this entire PR, really) `uuid` to `uid`

2021-09-01 17:43 UTC, shannynalayna commented on cli/src/main.rs
> +                        is_closed: if m.is_present("closed") {
I think based on how the flags are being used, I am not sure I can think of a cleaner way to this either really

2021-09-01 17:46 UTC, shannynalayna commented on cli/src/actions/purchase_orders.rs
> +                .unwrap_or_else(|_| "Cannot Format Purchase Order".to_string());
I think this function should return a `CliError`, so it is logged and output to the user rather than just output to the user

2021-09-14 20:19 UTC, KevinAnsleyJohnson commented on sdk/src/client/purchase_order/reqwest.rs
> +fn boolean_to_str(value: &bool) -> &'static str {
to_string() works for a String, but I can't to .to_string().as_str() because the temporary is freed while still in use... that's why I introduced the static str method. Is there a different way to do this?

2021-09-14 20:19 UTC, KevinAnsleyJohnson commented on cli/src/actions/purchase_orders.rs
> +use std::time::SystemTime;
fixed in latest version!

2021-09-15 19:48 UTC, shannynalayna commented on sdk/src/client/purchase_order/reqwest.rs
> +fn boolean_to_str(value: &bool) -> &'static str {
I think in this case, we can put a `&` in front of `is_closed.to_string()` and that will be the right type to add it to the hashmap. So it would look like this when you add the bool value to a hashmap: 
`filter_map.insert("is_closed", &is_closed.to_string());`

2021-09-20 16:15 UTC, KevinAnsleyJohnson commented on sdk/src/client/purchase_order/reqwest.rs
> +fn boolean_to_str(value: &bool) -> &'static str {
Unfortunately, it still causes a temporary is freed while still in use... this is due to the `If let Some` statement.

2021-09-27 16:10 UTC, shannynalayna approved these changes

2021-09-27 16:11 UTC, dnewh approved these changes

2021-09-27 16:11 UTC, leebradley approved these changes

2021-11-02 16:08 UTC, shannynalayna commented
This PR is being closed in favor of this PR: https://github.com/hyperledger/grid/pull/1008, which is more up-to-date with the current po structures

2021-11-02 16:08 UTC, closed without merging