Add purchase order version endpoint
hyperledger/grid pull request #957
Opened 2021-09-28 16:32 UTC by leebradley

Add an endpoint to obtain purchase order versions at
/purchase-order/{UUID}/versions.

Signed-off-by: Lee Bradley <bradley@bitwise.io>

2021-09-28 20:28 UTC, shannynalayna commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +    uuid: web::Path<String>,
Can you update this argument to be `uid` as the purchase order id was previously updated from `uuid` -> `uid` (throughout other components in Grid)

2021-09-28 20:29 UTC, shannynalayna commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +    uuid: web::Path<String>,
Including the openapi spec, we can make these updates as you are implementing each endpoint. But it might be worthwhile as apart of these tasks to verify the openapi spec is up to date

2021-09-29 18:05 UTC, shannynalayna commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +                Ok(res) => HttpResponse::Ok().json(res.version_numbers),
It looks like this will return just the version ids for the specified PO, but we want to be returning a list of the `PurchaseOrderVersion` objects. Could we use the store's `list_purchase_order_versions` here? You can specify the purchase order's ID & service id for that op

2021-10-01 17:11 UTC, shannynalayna submitted a review, later dismissed

2021-10-01 18:34 UTC, dnewh requested changes

2021-10-01 18:34 UTC, dnewh commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +#[get("/purchase-order/{uid}/versions")]
Should this be `.../version` to match the other routes?

2021-10-01 18:44 UTC, leebradley commented on sdk/src/rest_api/actix_web_3/routes/purchase_orders.rs
> +#[get("/purchase-order/{uid}/versions")]
I agree. Updated the endpoints and spec so that all these version endpoints are singular.

2021-10-01 19:01 UTC, dnewh approved these changes

2021-10-01 21:47 UTC, shannynalayna approved these changes

2021-10-04 15:37 UTC, merged