Create PO in cli
hyperledger/grid pull request #968
Opened 2021-10-04 13:33 UTC by KevinAnsleyJohnson

Adding functionality to create purchase order. Based on the updated RFC,
we need buyer-org and seller-org instead or owning org. Changes are
reflected in the man pages as well as code.

Signed-off-by: Kevin Johnson <kevin_johnson@cargill.com>

2021-10-04 17:04 UTC, dnewh requested changes

2021-10-04 17:04 UTC, dnewh commented on cli/Cargo.toml
> +rand = "0.7"
This should be pulled in by the purchase-order feature

2021-10-04 17:06 UTC, shannynalayna commented on cli/src/main.rs
> +                                .help("ID of the organization which owns the Purchase Order"),
Perhaps we could change this "help" text to be more specific for the buyer and seller org options

2021-10-04 19:03 UTC, leebradley approved these changes

2021-10-04 20:11 UTC, KevinAnsleyJohnson commented on cli/Cargo.toml
> +rand = "0.7"
fixed!

2021-10-04 20:11 UTC, KevinAnsleyJohnson commented on cli/src/main.rs
> +                                .help("ID of the organization which owns the Purchase Order"),
fixed!

2021-10-05 19:48 UTC, shannynalayna approved these changes

2021-10-05 20:10 UTC, dnewh approved these changes

2021-10-05 20:17 UTC, merged