Add `grid po version update` CLI command
hyperledger/grid pull request #975
Opened 2021-10-06 21:10 UTC by dnewh

This adds and implements the `grid po version update` CLI command. This
    command is used to update one or more of the editable PO version fields.
    This command handles for adding a new revision if new PO XML is
    submitted.

2021-10-28 16:53 UTC, leebradley submitted a review, later dismissed

2021-11-01 19:26 UTC, leebradley submitted a review, later dismissed

2021-11-05 15:32 UTC, peterschwarz commented on sdk/src/client/purchase_order/mod.rs
> +    /// * `service_id` - The service ID to fetch the version from
The commit message doesn't match the change - looks like a doc comment typo fix

2021-11-05 15:36 UTC, agunde406 requested changes

2021-11-05 15:36 UTC, agunde406 commented on sdk/src/client/purchase_order/mod.rs
> +    /// * `service_id` - The service ID to fetch the version from
The commit is just fixing a typo, commit message should be updated

2021-11-05 15:36 UTC, agunde406 commented on cli/src/main.rs
> -                            .required(true)
Is this change related?

2021-11-08 19:05 UTC, shannynalayna commented on cli/man/grid-po-version-update.1.md
> +`--current-revision`
No longer needed

2021-11-08 19:06 UTC, shannynalayna requested changes

2021-11-08 19:06 UTC, shannynalayna commented on cli/man/grid-po-version-update.1.md
> +`--current-revision`
Also, this man page still refers to an "owning" organization which needs to be updated

2021-11-08 19:06 UTC, shannynalayna commented on cli/man/grid-po-version-update.1.md
> +`--current-revision`
Also the output for updating lower down in this page is incorrect

2021-11-09 19:11 UTC, dnewh commented on cli/src/main.rs
> -                            .required(true)
yes, this arg should not be required

2021-11-09 19:11 UTC, dnewh commented on sdk/src/client/purchase_order/mod.rs
> +    /// * `service_id` - The service ID to fetch the version from
updated

2021-11-09 19:11 UTC, dnewh commented on sdk/src/client/purchase_order/mod.rs
> +    /// * `service_id` - The service ID to fetch the version from
updated

2021-11-09 19:12 UTC, dnewh commented on cli/man/grid-po-version-update.1.md
> +`--current-revision`
updated

2021-11-09 19:20 UTC, shannynalayna submitted a review, later dismissed

2021-11-09 19:32 UTC, shannynalayna approved these changes

2021-11-09 19:33 UTC, leebradley approved these changes

2021-11-11 18:56 UTC, agunde406 approved these changes

2021-11-11 18:57 UTC, merged